Feat/table
Atom-Learning/components pull request #175
Opened 2021-06-22 13:02 UTC by shaneakins

### In this PR

Table component with multiple subcomponents:

- Table.Body component, which is comparable to the HTML tag <tbody>
- Table.Cell, which is comparable to the HTML tag <td>
- Table.Footer, which is comparable to the HTML tag <tfoot>
- Table.Header, which is comparable to the HTML tag <thead>
- Table.HeaderCell, which is comparable to the HTML tag <th>
- Table Row, which is comparable to the HTML tag <tr>

unit tests
documentation

Normal table with base text and padding styles (width added to constrain size for screenshot:
<img width="672" alt="Screen Shot 2021-06-22 at 14 58 33" src="https://user-images.githubusercontent.com/10671944/122929043-bfa22200-d36a-11eb-8ec8-25b1552aaf57.png">

Table with styling applied to various components:
<img width="546" alt="Screen Shot 2021-06-22 at 14 59 41" src="https://user-images.githubusercontent.com/10671944/122928919-9aadaf00-d36a-11eb-8439-658e99d246df.png">

2021-06-22 13:12 UTC, alexandrunemes commented on src/components/table/Table.test.tsx
> +// import { render } from 'jest/test-utils'
you forgot this commented import

2021-06-22 13:15 UTC, shaneakins commented on src/components/table/Table.test.tsx
> +// import { render } from 'jest/test-utils'
Oops - good eye. Thanks!

2021-06-22 14:00 UTC, alexandrunemes commented on src/components/table/Cell.tsx
> +  p: '$2 $3'
Is this something `stitches` recognises as `padding`?

2021-06-22 14:01 UTC, alexandrunemes approved these changes

2021-06-22 14:02 UTC, alexandrunemes commented on src/components/table/Cell.tsx
> +  p: '$2 $3'
nevermind :D i gave `stitches.ts` a read

2021-06-23 07:36 UTC, andoulla commented on src/components/table/Table.mdx
> +Best practice: Due to rendering issues with some browsers, adding borders to `Table.Row` is possible by styling the Table component with `border-collapse: collapse`; however, this practice is general
```suggestion
Best practice: Due to rendering issues with some browsers, adding borders to `Table.Row` is possible by styling the Table component with `border-collapse: collapse`; however, this practice is generally not recommended. The preferred method for adding borders is applying styles to the `Table.Cell` and `Table.HeaderCell` components.
```

2021-06-23 07:36 UTC, andoulla commented on src/components/table/Table.tsx
> +// import { CSSWrapper } from '~/utilities'
```suggestion

```

2021-06-23 12:00 UTC, thomasdigby reviewed
I think we ought to consider how this table will be used, we're keeping flexibility with styling and composing components within a table but the usage is a bit verbose. Can you imagine us using a further abstraction to make it easier to display a set schema of data with this table?

2021-06-23 12:17 UTC, andoulla commented on src/components/table/Header.tsx
> +import { styled } from '~/stitches'
I'm wondering if we should change the filename pattern here and use the same as in Carousel for consistency.


I think the file names should be TableFooter, TableHeader etc.

2021-06-23 13:31 UTC, hollg requested changes
This is looking great! Other than the very small changes I've commented, I agree with @thomasdigby that we should add some useful default styles. Ideally we should make it as easy as possible to render these components looking a) good and b) consistent with Atom's branding — otherwise we might end up with the first half dozen `Tables` in the app to all be manually styled totally differently.

I'd be very happy to weigh in on decisions about what those default styles should be if that would be helpful.

2021-06-23 13:31 UTC, hollg commented on src/components/table/Header.tsx
> +Header.displayName = 'Header'
I think these subcomponents' display names should be `TableHeader`, `TableFooter` etc so that their names are clear out of context.

2021-06-23 13:31 UTC, hollg commented on src/components/table/Table.test.tsx
> +      <Table css={{ height: 100, width: 400, color: '$primary500' }}>
I'm being _real_ picky here, but can we use values like `"100px"` rather than `100`? `100` is totally valid, but I think it's worth being as inescapably clear as possible since we do have some "magic" numbers in the design system.

2021-06-23 13:31 UTC, hollg commented on src/components/table/Table.tsx
> +}: TableProps) => <StyledTable {...restProps}>{children}</StyledTable>
Since we're passing all the props on to one component here, we can simplify this to:

```tsx
export const Table: React.FC<TableProps> & TableSubComponents = (props: TableProps) => <StyledTable {...props}/>
```

I _think_ you can also get rid of the type declaration for `props` because it's impled by `React.FC<TableProps>`

2021-06-23 14:11 UTC, shaneakins commented on src/components/table/Table.tsx
> +}: TableProps) => <StyledTable {...restProps}>{children}</StyledTable>
Amazing! Thanks for the tip :)

2021-06-23 14:18 UTC, shaneakins commented on src/components/table/Header.tsx
> +import { styled } from '~/stitches'
Carousel uses dot notation. After I noticed that, I figured it was best to stick with the pattern:
<img width="668" alt="Screen Shot 2021-06-23 at 16 17 14" src="https://user-images.githubusercontent.com/10671944/123113135-98b52000-d43e-11eb-9c46-3522e8afb9a6.png">

2021-06-23 14:22 UTC, hollg commented on src/components/table/Header.tsx
> +import { styled } from '~/stitches'
The individual subcomponents are called `CarouselPagination`, `CarouselArrows` etc. But then we do `Carousel.Arrows = CarouselArrows`. This ensures that the component has a complete name wherever you look at it (and we could make a separate `Pagination` component later with no clashes).

2021-06-23 14:32 UTC, shaneakins commented on src/components/table/Table.test.tsx
> +      <Table css={{ height: 100, width: 400, color: '$primary500' }}>
Sure, will do

2021-06-23 14:36 UTC, shaneakins commented on src/components/table/Table.mdx
> +      <Table.Cell css={{border: '1px solid $tonal300'}}>35</Table.Cell>
That's a question I meant to ask: should I keep it unstyled except for basics like the text and spacing ,or style it with our standard (blue heading with white text and horizontal borders) and have that as default?

2021-06-23 14:38 UTC, shaneakins commented on src/components/table/Table.mdx
> +<Table css={{ height: 100, width: 400, color: '$primary500' }}>
Good catch - that was old code just to make sure things worked. Will update

2021-06-23 14:39 UTC, shaneakins commented on src/components/table/Header.tsx
> +import { styled } from '~/stitches'
Ahh gotcha - the actual filenames! Will update

2021-06-29 07:39 UTC, hollg commented on src/components/table/Header.tsx
> +import { styled } from '~/stitches'
Have you pushed your latest changes? The filenames don't seem to have been updated

2021-06-29 07:42 UTC, hollg commented on src/components/table/Table.test.tsx
> +      <Table css={{ height: 100, width: 400, color: '$primary500' }}>
This also hasn't been updated

2021-06-29 07:46 UTC, hollg commented on src/components/table/Table.tsx
> +}: TableProps) => <StyledTable {...restProps}>{children}</StyledTable>
This also hasn't been updated

2021-06-29 08:55 UTC, hollg commented on src/components/table/Table.mdx
> +      <Table.Cell css={{border: '1px solid $tonal300'}}>35</Table.Cell>
I think this probably needs to be properly answered to get the PR merge-ready. I agree with @thomasdigby that there are some useful styles we can add without getting too opinionated which would be a v good start.

I also think we should have a couple of variants, so that we can do something like `variant="primary"` and get the styling in the first example from the screenshot in this PR's description. But I don't know whether we have any designs that use a table yet, so perhaps it's worth waiting to base variants on those? Keen to hear opinions on that.

2021-06-29 09:08 UTC, hollg commented
> I think we ought to consider how this table will be used, we're keeping flexibility with styling and composing components within a table but the usage is a bit verbose. Can you imagine us using a further abstraction to make it easier to display a set schema of data with this table?

I think this is a v important question too. Most times you render a table, you have an array of objects for the rows so you do something like this, which when combined with whatever logic you need in each row and the markup for the header and footer, gets _real_ noisy.

```tsx
<Table>
{
  data.map(item => {
    return (<Table.Row>
      <Table.Cell>{item.id}</Table.Cell>
      { /* etc */}
    </Table.Row>
  }
}
</Table>
```

I've seen lots of table components that take some sort of `data` prop and make some assumptions about how it should be processed, but they've always also had escape hatches so that you can override the default logic, because invariably there will be exceptions to what you want to render.

@thomasdigby did you have any specific idea in mind for the abstraction you mentioned? If you do then I think it could be worth getting it included in this PR but if not then designing a good one might take a while and I'm conscious that this PR has been open a while and we might be blocking some of @shaneakins's work — could be something to revisit?

2021-06-29 10:32 UTC, shaneakins commented on src/components/table/Table.mdx
> +      <Table.Cell css={{border: '1px solid $tonal300'}}>35</Table.Cell>
Atanas created a new table design that I've been using as a point of reference: [Atom Assessment Entrance Exams](https://www.figma.com/file/lXBJN5xPUgN6oUTcfSP01j/Atom-Assessments?node-id=412%3A0). To be clear, are you suggesting to make `variant="primary"` and set that as default, similar to how the Button component functions?

2021-06-29 10:34 UTC, shaneakins commented on src/components/table/Header.tsx
> +import { styled } from '~/stitches'
Filenames have been updated - feel free to recheck

2021-06-29 10:34 UTC, shaneakins commented on src/components/table/Header.tsx
> +Header.displayName = 'Header'
Display names have been updated - feel free to recheck

2021-06-29 10:34 UTC, shaneakins commented on src/components/table/Table.test.tsx
> +      <Table css={{ height: 100, width: 400, color: '$primary500' }}>
Test has been updated - feel free to recheck

2021-06-29 10:34 UTC, shaneakins commented on src/components/table/Table.tsx
> +}: TableProps) => <StyledTable {...restProps}>{children}</StyledTable>
Refactor has been implemented - feel free to recheck

2021-06-29 11:54 UTC, hollg approved these changes

2021-06-29 12:33 UTC, thomasdigby commented on src/components/table/Table.mdx
> +      <Table.Cell css={{border: '1px solid $tonal300'}}>35</Table.Cell>
I don't think we should lean on variants until we have multiple to choose from, for now lets style this as per Atanas' designs, applying those styles when using it doesn't feel that great a DX to me.

2021-06-29 12:37 UTC, thomasdigby commented
> > I think we ought to consider how this table will be used, we're keeping flexibility with styling and composing components within a table but the usage is a bit verbose. Can you imagine us using a further abstraction to make it easier to display a set schema of data with this table?
> 
> I think this is a v important question too. Most times you render a table, you have an array of objects for the rows so you do something like this, which when combined with whatever logic you need in each row and the markup for the header and footer, gets _real_ noisy.
> 
> ```tsx
> <Table>
> {
>   data.map(item => {
>     return (<Table.Row>
>       <Table.Cell>{item.id}</Table.Cell>
>       { /* etc */}
>     </Table.Row>
>   }
> }
> </Table>
> ```
> 
> I've seen lots of table components that take some sort of `data` prop and make some assumptions about how it should be processed, but they've always also had escape hatches so that you can override the default logic, because invariably there will be exceptions to what you want to render.
> 
> @thomasdigby did you have any specific idea in mind for the abstraction you mentioned? If you do then I think it could be worth getting it included in this PR but if not then designing a good one might take a while and I'm conscious that this PR has been open a while and we might be blocking some of @shaneakins's work — could be something to revisit?

Yeah exactly, I think we should definitely export the table as is, the individual parts of the table fit the primitives model that we're using elsewhere. However for this to be _really_ useful I think we probably ought to provide the abstraction layer that maps data onto the table like @hollg suggests. This could (should) be a separate component and we can discuss the use case for that when delving into filterable/sortable tables, but it will broadly follow the same concept that `react-table` uses e.g. `columns` & `data`.

Let's not hold this PR up any longer, @hollg can you run through @shaneakins replies to your comments and resolve if necessary.

2021-06-29 12:39 UTC, thomasdigby commented on src/components/table/Table.tsx
> +  props: TableProps
We don't need this second type validation here, `React.FC<TableProps>` should be enough

2021-06-29 12:40 UTC, thomasdigby commented on src/components/table/TableFooterCell.tsx
> +  color: '$primary500',
Is this colour choice reflected in the designs? If not it might be worth defaulting to bold dark grey text instead

2021-06-29 12:40 UTC, thomasdigby approved these changes

2021-06-29 13:25 UTC, merged