Fix: Tabs mobile view
Atom-Learning/components pull request #259
Opened 2021-11-18 11:03 UTC by avirati

## Tabs Mobile View

### Tasks Undertaken
1. Based on total width of tab container and screen size, show `<` & `>` buttons to allow easy scrolling of tabs.
2. Scroll amount is at 25% of tab container width
3. Conditionally show / hide scroll buttons
4. Bring the components up to new design - supporting two variations

```typescript
<Tabs appearance="light"></Tabs>
<Tabs appearance="dark"></Tabs>
```

### Demo

#### Desktop
https://user-images.githubusercontent.com/1936119/142402905-7f749c94-1704-4724-b0a5-5ae5db754703.mov

#### Mobile
https://user-images.githubusercontent.com/1936119/142402968-9b3edec9-949a-44e0-a218-59de1c583e55.mov

2021-11-18 11:08 UTC, hollg commented on src/components/tabs/TabsTriggerList.tsx
> +      const scrollAmount = Math.round(scrollWidth / 4) // 25% of whole scroll width
How was `25%` decided on? I'm just wondering whether it will be possible that on some screen widths, not all tabs would be accessible because 25% would scroll you too far past them

2021-11-18 11:12 UTC, hollg commented on src/components/tabs/TabsTriggerList.tsx
> +      if (direction === 'right') {
Could this two-level nested `if` be avoided if we did `if (direction === 'right' && triggerList.scrollLeft + scrollAmount <= scrollWidth)` here?

2021-11-18 11:12 UTC, avirati commented on src/components/tabs/TabsTriggerList.tsx
> +      const scrollAmount = Math.round(scrollWidth / 4) // 25% of whole scroll width
That's a great point. Here is the slack discussion [thread](https://atom-learning.slack.com/archives/G01G926F9DM/p1637147852018100?thread_ts=1637147252.013600&cid=G01G926F9DM)

2021-11-18 11:14 UTC, avirati commented on src/components/tabs/TabsTriggerList.tsx
> +      if (direction === 'right') {
I think not, because we also have an else block inside, which requires `triggerList` to be truthy. Let me know if I am misunderstanding something

2021-11-18 11:16 UTC, hollg commented on src/components/tabs/TabsTriggerList.tsx
> +          left: scrollLeft - scrollAmount > 0 ? scrollLeft - scrollAmount : 0,
If we have two conditional branches where we call the same function (`triggerList.scroll`) and just pass different values in, I'd be keen to simplify the code so that there's only one call. E.g.

```
const leftValue = someCondition ? someAmount : someOtherAmount
triggerList.scroll({ left: leftValue, behaviour: 'smooth' })
```

Maybe we'd need to use `if` rather than a ternary, to avoid lots of ternary nesting, but I think that still ends up a little easier to follow.

2021-11-18 11:18 UTC, hollg commented on src/components/tabs/TabTrigger.tsx
> +  transition: '0.5s'
Half a second feels quite long to me — could we try something shorter?

2021-11-18 13:26 UTC, thomasdigby commented on src/components/tabs/Tabs.tsx
> +        'div[role="tab"]': {
I understand why you've brought these styles up to the `Tab` component, but I'd rather pass the `appearance` down as a prop to correctly co-locate and encapsulate the styles within each sub-component. e.g.

```tsx
export const Tabs: React.FC<TabsProps> & {
  TriggerList: typeof TriggerListWrapper
  Trigger: typeof TabTrigger
  Content: typeof StyledTabContent
} = ({ appearance = 'light', children, ...remainingProps }) => (
  <StyledRoot appearance={appearance} {...remainingProps}>
    {React.Children.map(children, (child) => {
      // you may need something similar within `TriggerListWrapper` to handle `TabTrigger`
      if (child.type === TriggerList || child.type === StyledTabContent) {
        return React.cloneElement(child, { appearance })
      }
    )}
  </StyledRoot>
)
```

2021-11-18 13:27 UTC, thomasdigby commented on src/components/tabs/Tabs.tsx
> +    appearance: {
We should use `theme` as the variant name here, for consistency mainly.

2021-11-18 13:28 UTC, thomasdigby commented on src/components/tabs/Tabs.tsx
> +  px: '$2',
What's the reason for the extra padding on the container here?

2021-11-18 13:29 UTC, thomasdigby commented on src/components/tabs/Tabs.tsx
> +        'div[role="tab"]': {
I have more comments on the styles themselves but I'd prefer to add those when we've moved them to the component files 👍

2021-11-18 14:18 UTC, thomasdigby commented on src/components/tabs/Tabs.tsx
> +        'div[role="tab"]': {
If you need a reference for our `React.Children` usage in the design system, worth looking at https://github.com/Atom-Learning/components/blob/main/src/components/action-icon/ActionIcon.tsx

2021-11-18 14:21 UTC, andoulla commented on src/components/tabs/Tabs.tsx
> +          bg: 'white !important',
How come we need the important(s) here? I just had to ask

2021-11-18 14:21 UTC, andoulla commented on src/components/tabs/TabsTriggerList.tsx
> +  top: 'calc(50% - 20px)'
I'm not sure I follow this, why -20?

2021-11-18 14:21 UTC, andoulla commented on src/components/tabs/TabsTriggerList.tsx
> +const StyledActionIcon = styled(ActionIcon, {
I would call them `StyledChevronIcon` as it is very explicit that they are (similar to the carousel component)

2021-11-18 14:21 UTC, andoulla commented on src/components/tabs/Tabs.tsx
> +            bg: opacify(-0.9, theme.colors.primary.value)
This is just for my benefit but where is this function coming from. When I google it I only get the SASS function for it

2021-11-19 05:51 UTC, avirati commented on src/components/tabs/TabTrigger.tsx
> +  transition: '0.5s'
Sure, this is how it looks with 0.3s

https://user-images.githubusercontent.com/1936119/142572164-6ac39fe5-257e-4aae-97d1-648f98d1e6d9.mov

2021-11-19 05:55 UTC, avirati commented on src/components/tabs/Tabs.tsx
> +  px: '$2',
Designs indicate slight padding on the left. Kept it on x axis to keep it consistent
https://www.figma.com/file/WLQxMluFW4OnaxXL03Gygw/Critique-Design?node-id=430%3A579

2021-11-19 05:56 UTC, avirati commented on src/components/tabs/Tabs.mdx
> +It also takes a `appearance` prop that should either be "light" or "dark".
That's up to the user to decide, I think. But I am open to further discussions

2021-11-19 06:07 UTC, avirati commented on src/components/tabs/TabsTriggerList.tsx
> +  top: 'calc(50% - 20px)'
The button that gets rendered has a size of 40px. This intends to horizontally align an absolute positioned element. Interested in knowing if there is a better way to handle this

2021-11-19 06:10 UTC, avirati commented on src/components/tabs/TabsTriggerList.tsx
> +
Great, thanks ! Have made it so

2021-11-19 06:13 UTC, avirati commented on src/components/tabs/Tabs.tsx
> +            bg: opacify(-0.9, theme.colors.primary.value)
Coming from `polished`

```typescript
import { opacify } from 'polished'
```

This was suggested by @thomasdigby and previously used (and probably introduced) by @Mhoog in some places

2021-11-19 06:15 UTC, avirati commented on src/components/tabs/Tabs.tsx
> +          bg: 'white !important',
We don't, had put them for quick testing and forgot afterwards. Rectified. Apologies !

2021-11-19 06:28 UTC, avirati commented on src/components/tabs/Tabs.tsx
> +        'div[role="tab"]': {
Makes complete sense ! Thanks. On it 👍

2021-11-19 09:53 UTC, hollg commented on src/components/tabs/TabTrigger.tsx
> +  transition: '0.5s'
Cool! I think this looks good but @thomasdigby usually has opinions on this so it might be worth waiting for his approval on it 😄

2021-11-19 10:04 UTC, hollg commented on src/components/tabs/TabsTriggerList.tsx
> +      if (direction === 'right') {
Sorry Avi I'm not sure I follow. Maybe my first comment wasn't clear! The `else` isn't nested within the `if (direction === 'right')` conditional block so I don't see changing that condition should affect it.

Does logic like this not work?

```
if (triggerList) {
  const { scrollWidth, scrollLeft } = triggerList
  const scrollAmount = Math.round(scrollWidth / 4) // 25% of whole scroll width
  
  if (direction === 'right' && triggerList.scrollLeft + scrollAmount <= scrollWidth) {
     triggerList.scroll({
            left: triggerList.scrollLeft + scrollAmount,
            behavior: 'smooth'
          })
  } else {
    triggerList.scroll({
      left: scrollLeft - scrollAmount > 0 ? scrollLeft - scrollAmount : 0,
      behavior: 'smooth'
    })
  }
} 
```

2021-11-19 10:19 UTC, thomasdigby commented on package.json
> +    "jest": "^26.6.3",
What's the reason for this downgrade?

2021-11-19 10:22 UTC, avirati commented on src/components/tabs/TabsTriggerList.tsx
> +      if (direction === 'right') {
That's an old comment @hollg 
It looks like this now

```typescript
if (triggerList) {
      const { scrollWidth, scrollLeft } = triggerList
      const scrollAmount = Math.round(scrollWidth / 4) // 25% of whole scroll width
      let left = scrollLeft
      if (direction === 'right') {
        const newScrollAmount = triggerList.scrollLeft + scrollAmount
        left = newScrollAmount <= scrollWidth ? newScrollAmount : scrollLeft
      } else {
        const newScrollAmount = scrollLeft - scrollAmount
        left = newScrollAmount > 0 ? newScrollAmount : 0
      }

      triggerList.scroll({
        left,
        behavior: 'smooth'
      })
...
}
```

2021-11-19 10:22 UTC, thomasdigby commented on src/components/tabs/Tabs.tsx
> +  px: '$2',
I think that may be incidental, these values seem to represent spacing between the tab container and other sibling elements, so I would remove them and if they're required allow the user to add them when needed.

2021-11-19 10:24 UTC, avirati commented on package.json
> +    "jest": "^26.6.3",
Had to downgrade to fix this error (while trying to locally test things, didn't succeed :()
https://atom-learning.slack.com/archives/C02EZ3H6P1U/p1637300430197000?thread_ts=1637232841.193900&cid=C02EZ3H6P1U

2021-11-19 10:26 UTC, hollg commented on src/components/tabs/TabsTriggerList.tsx
> +      if (direction === 'right') {
Apologies! New version looks great 👍🏻

2021-11-19 10:27 UTC, avirati commented on src/components/tabs/Tabs.tsx
> +  px: '$2',
Roger that, on it 👍

2021-11-19 10:35 UTC, avirati commented on src/components/tabs/TabsTriggerList.tsx
> +      const scrollAmount = Math.round(scrollWidth / 4) // 25% of whole scroll width
@thomasdigby need your input here

2021-11-19 10:43 UTC, andoulla commented on src/components/tabs/Tabs.mdx
> +It also takes a `appearance` prop that should either be "light" or "dark".
Talking to jessica they had specific use cases for when to use the dark one but happy to come back and add more docs when things are finalised

2021-11-19 10:54 UTC, andoulla approved these changes

2021-11-19 11:02 UTC, avirati commented on src/components/tabs/TabsTriggerList.tsx
> +  top: 'calc(50% - 20px)'
Changed to calc(50% - ($4 + $1)), thanks @andoulla for showing me the this !

2021-11-19 13:24 UTC, thomasdigby commented on src/components/tabs/Tabs.tsx
> +        fontFamily: '$body'
We can move this to default styles as it doesn't change per variant

2021-11-19 13:28 UTC, thomasdigby commented on src/components/tabs/utils.ts
> +    if (allowedChildNodeTypes.includes(child?.type)) {
We may need to add a check for a valid react element here, TS has thrown an error in the past when I haven't included this

```ts
if (!React.isValidElement(child)) {
  throw new Error()
}
```

2021-11-19 13:34 UTC, thomasdigby commented on src/components/tabs/TabsTriggerList.tsx
> +          role="scrollbar"
Is `role="scrollbar"` the correct role for this component? Reading on the W3 spec it seems like this is specifically for a scrollbar and not the controls for the scrollbar https://www.w3.org/TR/wai-aria-1.1/#scrollbar

2021-11-19 14:40 UTC, thomasdigby commented on src/components/tabs/TabsTriggerList.tsx
> +      const scrollAmount = Math.round(scrollWidth / 4) // 25% of whole scroll width
I actually am not super clear on Gary's point.

25% is relative to the width of the container for the tab trigger list, not the total scrollable length of the trigger list. So for example, if we have two tabs at 100% and 50% of the width of the container and we scroll along at 25% of the container width, the first tab will have 75% in view, and the second will be 25% in view. No matter the size of the tab, with each scroll left/right you're only moving the tab 25% of the container width in either direction.

I might not have described that well, please let me know if I haven't

2021-11-19 14:43 UTC, hollg commented on src/components/tabs/TabsTriggerList.tsx
> +      const scrollAmount = Math.round(scrollWidth / 4) // 25% of whole scroll width
I had definitely misunderstood what that `25%` represents, will resolve this thread. Thanks Tom!

2021-11-19 14:44 UTC, thomasdigby commented on src/components/tabs/TabsTriggerList.tsx
> +      const scrollAmount = Math.round(scrollWidth / 4) // 25% of whole scroll width
Oh, I've just realised what you mean, we should be using `clientWidth` instead of `scrollWidth` here, to ensure that we're scrolling 25% of the container width, not of the content width.

And with that in mind, I wonder whether 33% (or even 50%) might work better at smaller viewport sizes

2021-11-19 14:45 UTC, thomasdigby commented on src/components/tabs/TabsTriggerList.tsx
> +      }, 300)
Is this value consistent cross-browser?

2021-11-19 14:46 UTC, thomasdigby commented on src/components/tabs/TabsTriggerList.tsx
> +            label="scroll-right"
Can we treat this label as human readable text? e.g.

```suggestion
            label="Scroll right"
```

2021-11-19 14:46 UTC, thomasdigby commented on src/components/tabs/TabsTriggerList.tsx
> +            '&::-webkit-scrollbar': { display: 'none' }
Do we need any other properties to hide/remove the scrollbar cross-browser?

2021-11-19 14:48 UTC, thomasdigby commented on src/components/tabs/TabsTriggerList.tsx
> +  }, [])
We should look to add this functionality on resize as well

2021-11-19 14:50 UTC, thomasdigby commented on src/components/tabs/TabsTriggerList.tsx
> +  top: 'calc(50% - ($4 + $1))',
If we want the `ActionIcon` to be the height of the trigger list, we should be able to set `top: 0` right? Does the `ActionIcon` not match the height at the moment?

2021-11-19 14:51 UTC, thomasdigby commented on src/components/tabs/TabsTriggerList.tsx
> +            '&::-webkit-scrollbar': { display: 'none' }
Also, we can just add these CSS properties to the `StyledTriggerList` itself, rather than passing them down through `css={}`

2021-11-19 14:59 UTC, thomasdigby commented on src/components/tabs/TabsTriggerList.tsx
> +        '&[role="scrollbar"], &[role="scrollbar"]:not(:disabled):hover, &[role="scrollbar"]:not(:disabled):focus, &[role="scrollbar"]:not(:disabled):active': {
Are we overriding the default theme of the `ActionIcon` here? Is that why we're adding the extra specificity? It would be great if we were able to write something like this to handle that and simplify the selectors:

```ts
const StyledChevronIcon = styled(ActionIcon, {
  color: 'currentColor',
  position: 'absolute',
  top: 'calc(50% - ($4 + $1))',
  variants: {
    theme: {
      light: {
        '&, &:hover, &:focus, &:active': { bg: fadedWhite }
      },
      dark: {
        '&, &:hover, &:focus, &:active': { bg: fadedPrimaryDark }
      }
    }
  }
})
```

2021-11-19 15:17 UTC, thomasdigby commented on src/components/tabs/TabsTriggerList.tsx
> +    <StyledTriggerList css={css} theme={theme} {...rest} ref={triggerListRef}>
We should be able to pass `css` as part of `{...rest}` so we can remove it here and in our props

2021-11-19 15:20 UTC, thomasdigby commented on src/components/tabs/TabTrigger.tsx
> +  transition: '0.5s'
I have _opinions!?_ I think this looks good 👍

2021-11-19 15:23 UTC, thomasdigby commented on src/components/tabs/TabTrigger.tsx
> +          textShadow: '0px 0px 1px currentColor',
Are we using this in lieu of `fontWeight: 'bold'`? I think we need to set every tab as either `bold` or `normal` so we can avoid the pixel jump when selecting a tab

2021-11-19 15:23 UTC, thomasdigby commented
Added a bunch of comments, mostly minor changes, but overall it's looking great. Excited to get this in! 👍

2021-11-22 07:31 UTC, avirati commented on src/components/tabs/TabsTriggerList.tsx
> +          role="scrollbar"
I see, should it just be "button" then ?

2021-11-22 08:17 UTC, avirati commented on src/components/tabs/TabsTriggerList.tsx
> +      }, 300)
It is, since other browsers do not have a smooth animation inbuilt, it's almost immediate, snappy. Which makes me wonder, are we okay with that ?

2021-11-22 08:30 UTC, avirati commented on src/components/tabs/TabsTriggerList.tsx
> +      }, 300)
Do you think `500` would be a better alternate ?

2021-11-22 08:40 UTC, avirati commented on src/components/tabs/TabsTriggerList.tsx
> +            '&::-webkit-scrollbar': { display: 'none' }
Added `scrollbarWidth: 'none'` for firefox to hide the scrollbar.
Moved the css properties above to `StyledTriggerList` ✔️

2021-11-22 09:18 UTC, avirati commented on src/components/tabs/TabsTriggerList.tsx
> +  top: 'calc(50% - ($4 + $1))',
ActionIcon is 40px in size whereas the tabs are 49px in height. Do you think they should have / could be matched ?

2021-11-22 09:24 UTC, avirati commented on src/components/tabs/TabsTriggerList.tsx
> +        '&[role="scrollbar"], &[role="scrollbar"]:not(:disabled):hover, &[role="scrollbar"]:not(:disabled):focus, &[role="scrollbar"]:not(:disabled):active': {
My initial hunch was this but I think the additional specificity is required to properly override css pseudo states

2021-11-22 09:29 UTC, avirati commented on src/components/tabs/TabTrigger.tsx
> +          textShadow: '0px 0px 1px currentColor',
Yes, I used textShadow which was inspired from a previous implementation of tabs in our code. I also understand what you are trying to imply here, that we set aside a fixed sized text so that the jump does not happen, however while implementing this, I still see the jump. Perhaps you could help me out here with some more examples / reading material. Interested to know how this can be solved

2021-11-22 20:57 UTC, thomasdigby requested changes
Apologies for another flurry of comments, I just want to make sure that we get this right. I think this should be good once we work through the last few bits 👍

2021-11-22 20:57 UTC, thomasdigby commented on src/components/tabs/TabTrigger.tsx
> +          textShadow: '0px 0px 1px currentColor',
Huh, I don't know why it would jump if each tab is `bold`, let's chat about this in person when you're available. We should avoid using `textShadow` for bolding anyway as it'll render a "faux bold" style that won't match with the actual bold weight that the typeface provides. This article is almost 10 years old (!) but it still holds true https://alistapart.com/article/say-no-to-faux-bold/

2021-11-22 20:57 UTC, thomasdigby commented on src/components/tabs/TabTrigger.tsx
> +  <StyledTabTrigger css={css} disabled={disabled} theme={theme} {...otherProps}>
```suggestion
  <StyledTabTrigger disabled={disabled} theme={theme} {...otherProps}>
```

2021-11-22 20:57 UTC, thomasdigby commented on src/components/tabs/utils.ts
> +  allowedChildNodeTypes: any[] = []
Could we tighten up this type?

```suggestion
  allowedChildNodeTypes: ReactElement[] = []
```

2021-11-22 20:57 UTC, thomasdigby commented on src/components/tabs/TabsTriggerList.tsx
> +      const scrollAmount = Math.round(scrollWidth / 4) // 25% of whole scroll width
@avirati Can you confirm that we don't need to use `clientWidth` here?

2021-11-22 20:57 UTC, thomasdigby commented on src/components/tabs/TabsTriggerList.tsx
> +  top: 'calc(50% - ($4 + $1))',
The tabs should have a set height, I'm surprised they haven't got one. I'd use this opportunity to set a height on tabs so we can match with the `ActionIcon`. `$sizes$5` is 48px which should work well. You may need to set a height here using `size: $5` as well.

2021-11-22 20:57 UTC, thomasdigby commented on src/components/tabs/Tabs.tsx
> +import React from 'react'
Why did we switch to the interop default import here?

2021-11-22 20:57 UTC, thomasdigby commented on src/components/tabs/TabsTriggerList.tsx
> +  scrollbarWidth: 'none',
It might be a nice improvement to add these properties to a custom utility in our stitches config, e.g.

```ts
scrollbar: 'none'
```

```ts
scrollbar: () => ({
  '&::-webkit-scrollbar': { display: 'none' },
  scrollbarWidth: 'none'
})
```

Maybe one for the backlog rather than this PR

2021-11-22 20:57 UTC, thomasdigby commented on src/components/tabs/TabsTriggerList.tsx
> +            role="scrollbar"
Can't reply to the original comment, but we should just remove this `role`, the `ActionIcon` component already renders a button

2021-11-22 20:57 UTC, thomasdigby commented on src/components/tabs/Tabs.test.tsx
> +    expect(container).toMatchSnapshot()
Does this render the scrolling buttons? I couldn't see anything matching them in the snapshot

2021-11-23 07:24 UTC, avirati commented on src/components/tabs/TabsTriggerList.tsx
> +      const scrollAmount = Math.round(scrollWidth / 4) // 25% of whole scroll width
@thomasdigby @hollg , What I had in mind was, let's say we have 20 tabs in the container with very small width, 25% of `scrollWidth` would probably scroll 5 items at once. `clientWidth` would certainly solve that problem to some extent, but I wouldn't want to increase the percentage.

Ideally, I would want it to snap (and select / focus) one tab at a time, per scroll click - think of google sheets scrolling, it snaps to one cell at a time. This can be handled in a separate ticket, though

2021-11-23 08:24 UTC, avirati commented on src/components/tabs/TabsTriggerList.tsx
> +  top: 'calc(50% - ($4 + $1))',
Set a fixed height to Tab.
Added a new variation to `size` prop of `ActionIcon` of `xl`, which equates to `$5`

2021-11-23 08:37 UTC, avirati commented on src/components/tabs/utils.ts
> +  allowedChildNodeTypes: any[] = []
TS was throwing errors, using `JSXElementConstructor<any>[]` instead.
`allowedChildNodeTypes: JSXElementConstructor<any>[] = []`

2021-11-23 08:38 UTC, avirati commented on src/components/tabs/Tabs.tsx
> +import React from 'react'
I think, it was unintentional. Will revert 👍

2021-11-23 09:08 UTC, avirati commented on src/components/tabs/TabsTriggerList.tsx
> +  scrollbarWidth: 'none',
Issue created and assigned to self
https://github.com/Atom-Learning/components/issues/263

2021-11-23 09:20 UTC, avirati commented on src/components/tabs/TabsTriggerList.tsx
> +            role="scrollbar"
Alright, but to achieve the needed specificity, would `!important` be acceptable ?

```typescript
const StyledChevronIcon = styled(ActionIcon, {
  position: 'absolute',
  variants: {
    theme: {
      light: {
        '&, &:not(:disabled):hover, &:not(:disabled):focus, &:not(:disabled):active': {
          bg: fadedWhite,
          color: 'currentColor'
        }
      },
      dark: {
        '&, &:not(:disabled):hover, &:not(:disabled):focus, &:not(:disabled):active': {
          bg: fadedPrimaryDark,
          color: 'currentColor !important'
        }
      }
    }
  }
})
```

2021-11-23 09:33 UTC, avirati commented on src/components/tabs/Tabs.test.tsx
> +    expect(container).toMatchSnapshot()
Strange, I'll investigate.

2021-11-23 09:51 UTC, avirati commented on src/components/tabs/TabsTriggerList.tsx
> +        '&[role="scrollbar"], &[role="scrollbar"]:not(:disabled):hover, &[role="scrollbar"]:not(:disabled):focus, &[role="scrollbar"]:not(:disabled):active': {
Resolving this since a parallel thread is open on the same

2021-11-23 10:11 UTC, avirati commented on src/components/tabs/Tabs.test.tsx
> +    expect(container).toMatchSnapshot()
was able to circumvent that by setting `display` on buttons, instead of conditionally rendering them

2021-11-23 10:46 UTC, avirati commented on src/components/tabs/Tabs.test.tsx
> +    expect(container).toMatchSnapshot()
Will try to solve this with opacity + visibility + pointer-events: none

2021-11-23 11:25 UTC, avirati commented on src/components/tabs/TabsTriggerList.tsx
> +      const scrollAmount = Math.round(scrollWidth / 4) // 25% of whole scroll width
Post discussion, it was decided that we would enhance it as per this feature request https://github.com/Atom-Learning/components/issues/264

Resolving this

2021-11-23 11:34 UTC, avirati commented on src/components/tabs/TabTrigger.tsx
> +          textShadow: '0px 0px 1px currentColor',
Post discussion, resolving this by setting fontWeight and negative letter spacing

2021-11-23 11:35 UTC, avirati commented on src/components/tabs/TabsTriggerList.tsx
> +            role="scrollbar"
Post discussion, `!important` seems unavoidable.

```typescript
const StyledChevronIcon = styled(ActionIcon, {
  position: 'absolute',
  variants: {
    theme: {
      light: {
        bg: `${fadedWhite} !important`
      },
      dark: {
        bg: `${fadedPrimaryDark} !important`,
        color: 'currentColor !important'
      }
    }
  }
})
```

2021-11-23 11:54 UTC, thomasdigby reviewed
Awesome, just two final bits then we're good to go

2021-11-23 11:54 UTC, thomasdigby commented on src/components/tabs/Tabs.tsx
> +  pt: '$4',
I'm still not clear as to why we need this `padding-top` here, can we remove it and apply it through `css` in core where it's required?

2021-11-23 11:54 UTC, thomasdigby commented on src/components/tabs/TabsTriggerList.tsx
> +        visibility: 'visible',
We need to add a `transition: all 125ms` to the base styles here to allow the icon to fade in and out

2021-11-23 12:11 UTC, avirati commented on src/components/tabs/Tabs.tsx
> +  pt: '$4',
Added it because the design had it, but yes I get your point, this should come from core

2021-11-23 12:22 UTC, thomasdigby approved these changes
Excellent work!

2021-11-23 12:34 UTC, thomasdigby approved these changes

2021-11-23 12:41 UTC, merged