feat: adding new table variants
Atom-Learning/components pull request #261
Opened 2021-11-22 15:00 UTC by kerryambt

Added a few options to the table as they were needed for use with Accordions, and will likely be useful in the future elsewhere.

- `<Table applyRadius="false">` stops borderRadius being applied, useful if your container has a radius and multiple radiuses look odd. Default is `true`.
- `<Table.Header theme="primary">` changes the colour of the header rows. Options are `primary` and `primaryDark`. Default is `primaryDark`.

![image](https://user-images.githubusercontent.com/66493855/142883482-3172197c-6e30-4357-a125-3360814a913b.png)

2021-11-22 15:55 UTC, andoulla commented on src/components/table/Table.test.tsx
> +        css={{ height: '100px', width: '400px', color: '$primary500' }}
if the table now has a default and a variant I don't think we should pass `color: '$primary500'` what do you think?

2021-11-22 15:55 UTC, andoulla commented on src/components/table/Table.tsx
> +  applyRadius = 'true',
why is true here a string?

2021-11-22 15:55 UTC, hollg commented
Does `<Table css={{borderRadius: 'none'}}/>` not work? 

I'd be keen to avoid boolean props like this where possible because once you start adding them it's easy to end up with components that aren't actually that flexible any more.

2021-11-22 16:02 UTC, hollg commented
Oh, sorry, I think I see the issue: there `border-radius` is applied to some header cells too. We could still use the `css` prop in each case, although with a more complicated value. 

If we want to avoid that then I'd recommend renaming the variant to something descriptive rather than imperative. E.g. `corners`: `soft` or `square`. That makes it more in keeping with the convention established by our other themes.

2021-11-22 16:08 UTC, kerryambt commented on src/components/table/Table.tsx
> +  applyRadius = 'true',
this was a typo, but I have changed it as per Gary's comments below.

2021-11-22 16:08 UTC, kerryambt commented on src/components/table/Table.test.tsx
> +        css={{ height: '100px', width: '400px', color: '$primary500' }}
sorry, missed that! removed.

2021-11-22 16:19 UTC, kerryambt commented
@hollg I think it would be helpful to have as a property rather than using css, mostly because the css required is pretty clunky given a simple `borderRadius: 'none'` doesn't work.

Really good point on the naming convention though. I was staring at true being what it was and it didn't look right but somehow didn't think to rename. Have now set to `corners="rounded"` or `corners="square"`.

2021-11-22 20:07 UTC, thomasdigby requested changes
Just a few minor changes I reckon, looking good though! Hat tip @hollg for the improved `corners` API suggestion

2021-11-22 20:07 UTC, thomasdigby commented on src/components/table/Table.tsx
> +      }
I think there's a further conversation to be had about the consistency with which we apply props that affect nested components, in other cases we've used `React.Children` to pass those props directly down to children, allowing the styles to stay co-located with the component. I'm happy with these styles for now but I think it'll be beneficial to bring them all in line and document the preferred method 👍

2021-11-22 20:07 UTC, thomasdigby commented on src/components/table/TableHeader.tsx
> +        '& th': {
Can we target the `th` by the same `[${TableHeaderCell}]` convention we're using elsewhere?

2021-11-23 09:48 UTC, kerryambt commented on src/components/table/TableHeader.tsx
> +        '& th': {
good point - done :)

2021-11-23 09:48 UTC, kerryambt commented on src/components/table/Table.mdx
> +<Table corners="square">...</Table>
thanks! me too

2021-11-23 09:53 UTC, kerryambt commented on src/components/table/Table.tsx
> +      }
these are both really interesting points. I think a frontend team chat would be beneficial to discuss our overall composition for components here, and then documentation when it's done. I've not personally used `React.Children` before but to me the idea of passing props down the tree makes more sense because the props are being used where they need to be. I'm happy with a little bit of potential prop drilling for the sake of easier to read code when we're composing components (though generally drilling isn't great). 

For now I'm going to apply your suggestions, I think there's merit however for a conversation and then maybe a task (perhaps as tech debt) to update components to whatever system we decide. It makes sense to me to do that all at once so this can stay as is for now.

2021-11-23 11:47 UTC, thomasdigby approved these changes

2021-11-23 12:47 UTC, merged