chore: wip empty state component
Atom-Learning/components pull request #329
Opened 2022-05-06 14:30 UTC by taniya-atomlearning

2022-05-11 11:21 UTC, taniya-atomlearning commented on src/components/empty-states/EmptyStates.tsx
> +          color: '$tonal400',
I had to add color here for each variant of the body as it seems to conflict with the styling of the title when added in the EmptyStatesBody component file.

2022-05-11 11:32 UTC, hollg requested changes
This is an extremely impressive first outing in the DS! 👏🏻 

I know the nested styling for the variants got a bit complex but the outcome seems like a really nice-to-use API. 

I've requested a few changes but they're mostly just housekeeping to keep this PR consistent with conventions you haven't really been exposed to before / tidying up from when we had those SVGs in the library directly.

2022-05-11 11:32 UTC, hollg commented on package.json
> +    "rollup-plugin-svg": "^2.0.0",
I believe we can get rid of this now, since the semicircle SVG isn't being stored in the library directly?

2022-05-11 11:32 UTC, hollg commented on rollup.config.js
> +import svg from 'rollup-plugin-svg'
We should be able to get rid of this (see prev comment)

2022-05-11 11:32 UTC, hollg commented on src/components/empty-states/EmptyStates.mdx
> +title: Empty States
This should be singular, i.e. `EmptyState`. Might be simplest to do a find and replace to catch all the references in code etc.

2022-05-11 11:32 UTC, hollg commented on src/components/empty-states/EmptyStates.test.tsx
> +describe('EmptyStates component', () => {
Could we snapshot each size variant?

2022-05-11 11:32 UTC, hollg commented on src/components/empty-states/EmptyStates.tsx
> +    <Box>
Is this `Box` still required? What does it do?

2022-05-11 11:32 UTC, hollg commented on types/custom.d.ts
> +declare module '*.svg' {
This can go now (see above comment)

2022-05-11 11:32 UTC, hollg commented on tsconfig.json
> +  "include": ["./src/*", "types/*"],
This is another change that was only required when we had svgs inside the library

2022-05-11 11:32 UTC, hollg commented on src/components/empty-states/EmptyStates.tsx
> +const StyledBox = styled(Flex, {
I think it would be nice to give this a descriptive name like you have with the other components. Something like `EmptyStateContainer`.

2022-05-11 11:32 UTC, hollg commented on src/components/empty-states/EmptyStatesBody.tsx
> +export const EmptyStatesBody = styled('p', {
Did you ever try using our `Text` component here instead of `'p'`? `Text` already has `fontFamily: '$body'` applied, so unless any other styles on it conflict with the designs for this component, it might save some repetition.

2022-05-11 11:32 UTC, hollg commented on src/components/empty-states/EmptyStates.tsx
> +          width: '84px',
`size` sets both `height` and `width` together when they have the same vlaue, e.g. `size: '84px'`

2022-05-11 11:34 UTC, andoulla commented on src/components/empty-states/EmptyStates.mdx
> +title: Empty States
I know this might sound minor but I think the component should be Empty State (singular) to match the pattern we have used for all the other components. (Button, Label etc).

Also, the plural kind of makes it sound that it is multiple states but it is only showing 1 empty state

2022-05-11 11:34 UTC, andoulla commented on src/components/empty-states/EmptyStates.tsx
> +          height: '32px',
could we use the size tokens for these? `width: '$4', height:'$3'`

2022-05-11 11:34 UTC, andoulla commented on src/components/empty-states/EmptyStates.tsx
> +          fontSize: '14px',
could we do fontSize: "sm" here?

https://design.atomlearning.technology/theme/typography

2022-05-11 11:34 UTC, andoulla commented on src/components/empty-states/EmptyStates.tsx
> +          fontSize: '16px',
fontSize: "$md"

2022-05-11 11:34 UTC, andoulla commented on src/components/empty-states/EmptyStates.tsx
> +const IllustrationContainer: React.FC<IllustrationContainerProps> = (props) => {
Why not separate this into its own component file like the title and the body?

2022-05-11 11:34 UTC, andoulla commented on src/components/empty-states/EmptyStates.tsx
> +const StyledBox = styled(Flex, {
Could we call this StyledContainer? Very very minor btw

2022-05-11 12:53 UTC, andoulla commented on src/components/empty-states/EmptyStates.mdx
> +title: Empty States
jinx

2022-05-11 12:54 UTC, andoulla commented on src/components/empty-states/EmptyStates.tsx
> +          color: '$tonal400',
the only concern is that we have a few empty states in assessments where we have a primary coloured body. Will we be able to overwrite this without the !important?

2022-05-11 13:47 UTC, taniya-atomlearning commented on src/components/empty-states/EmptyStates.tsx
> +          color: '$tonal400',
hmm not sure @hollg ?

2022-05-11 13:54 UTC, taniya-atomlearning commented on package.json
> +    "rollup-plugin-svg": "^2.0.0",
sure, will remove it wasn't sure whether it'll be useful to leave for future use

2022-05-11 14:45 UTC, taniya-atomlearning commented on src/components/empty-states/EmptyStates.test.tsx
> +describe('EmptyStates component', () => {
sure will add

2022-05-11 14:52 UTC, taniya-atomlearning commented on src/components/empty-states/EmptyStates.tsx
> +const StyledBox = styled(Flex, {
thanks, yea that makes sense

2022-05-11 14:55 UTC, taniya-atomlearning commented on src/components/empty-states/EmptyStates.tsx
> +          height: '32px',
In the design figma I don't have the tokens, is there a place I can see a list of these? @andoulla

2022-05-11 14:59 UTC, andoulla commented on src/components/empty-states/EmptyStates.tsx
> +          height: '32px',
https://design.atomlearning.technology/overview/introduction layout and space for this and typography for fonts

2022-05-11 15:00 UTC, taniya-atomlearning commented on src/components/empty-states/EmptyStates.tsx
> +          height: '32px',
Spoke to Miguel, he mentioned the pixels are different to the existing size tokens

2022-05-11 15:02 UTC, taniya-atomlearning commented on src/components/empty-states/EmptyStates.tsx
> +          height: '32px',
probably something to discuss with Miguel

2022-05-11 15:11 UTC, taniya-atomlearning commented on src/components/empty-states/EmptyStates.tsx
> +          color: '$tonal400',
As discussed @andoulla will leave the customisation for the EmptyStatesBody for v2 of the component

2022-05-11 15:42 UTC, taniya-atomlearning commented on src/components/empty-states/EmptyStates.tsx
> +const IllustrationContainer: React.FC<IllustrationContainerProps> = (props) => {
good shout will do

2022-05-11 15:47 UTC, taniya-atomlearning commented on src/components/empty-states/EmptyStates.tsx
> +          color: '$tonal400',
I changed the EmptyStateBody to use Text instead of p tag, I was able to move the color to the element level and we can customise the EmptyStateBody element now :)

2022-05-11 17:04 UTC, thomasdigby commented on src/components/empty-state/EmptyState.test.tsx
> +  })
I think that we're testing our CSS in JS lib here more than providing a useful test to ensure that the different sizes are rendered correctly. You'll see in the snapshot for this component that all size variant styles are rendered with each test; we could remove them all apart from one and just use that single test to ensure the styles are output correctly.

2022-05-12 07:41 UTC, taniya-atomlearning commented on src/components/empty-state/EmptyState.tsx
> +  alignItems: 'center',
Thanks Tom, not sure about the minimum height, will discuss with the team today. I'll add the padding for each variant

2022-05-12 07:41 UTC, taniya-atomlearning commented on src/components/empty-state/EmptyState.test.tsx
> +  })
ok thanks, will try that

2022-05-12 08:05 UTC, taniya-atomlearning commented on src/components/empty-state/EmptyState.test.tsx
> +  })
@thomasdigby  I couldn't find any examples in the components repo for this. but I tried something like this. Is this what you mean? Do you know any examples I could look at? Thanks
`  it('renders a component', async () => {
    const { container } = render(<SimpleExample size="lg" />)

    expect(container).toMatchSnapshot()

    const h2 = document.getElementsByTagName('h2')
    const style = window.getComputedStyle(h2[0])
    expect(style.fontWeight).toBe('')
    expect(style.fontFamily).toBe('')
    expect(style.fontSize).toBe('')
  })`

2022-05-12 08:19 UTC, taniya-atomlearning commented on src/components/empty-state/EmptyState.test.tsx
> +  })
sorry I might be misunderstanding your comment, do you mean just have a test with the basic component?
```  it('renders a component', async () => {
    const { container } = render(<SimpleExample />)

    expect(container).toMatchSnapshot()
  })

2022-05-12 08:22 UTC, thomasdigby commented on src/components/empty-state/EmptyState.test.tsx
> +  })
Yeah exactly, sorry that was my bad explanation. I think we can have a single test to check that it renders as expected

2022-05-12 08:28 UTC, taniya-atomlearning commented on src/components/empty-state/EmptyState.test.tsx
> +  })
ok thanks

2022-05-12 09:44 UTC, thomasdigby commented on src/components/empty-state/EmptyState.test.tsx
> +    const { container } = render(<EmptyState />)
Should this be `SimpleExample`? We'll want to test `EmptyState` with the relevant child components

2022-05-12 09:59 UTC, hollg commented on src/components/empty-state/EmptyState.tsx
> +      xs: {
This is super interesting and I think it's something we should establish a solid convention on. 

My gut feeling is that the reltionship being defined here is fundamentally about styling and that therefore it would be good to keep the logic in CSS (or rather CSS-in-JS) rather than in React code. Having one long file is definitely a cost to that approach, but we do have the option of splitting that big object into chunks and storing each chunk somewhere that feels more intuitive, e.g. nested styled for the title could be co-located with the title component.

That definitely isn't a perfect solution; we'd be introducing a layer of indirection between the definition of the container styles and the nested styles.

Maintaining the very dev-friendly API that Taniya has created is the priority imo, but I'd be keen to hear if you have any thoughts on the distinction between React code vs styling logic, and whether you think it matters etc @thomasdigby

2022-05-12 10:09 UTC, LimeWub commented on src/components/empty-state/EmptyState.tsx
> +      xs: {
For what it's worth - currently on my ToggleGroup component I've introduced a context for the sizing of the children (Which does exactly the same thing as cloneElement, and I could also use cloneElement but I think context is more flexible when it comes to nesting and there was not any loss to using it here afaik (?) Anyway!). So I'm with @thomasdigby here

Compared to having all the size styles on the parent; passing down a size prop was better for me because a) it's easier to read and manage and b) there's a chance the children can be of different visual styles, like a Card vs a Button and it was much cleaner to keep the size related differences in the elements themselves rather than having messy styling on the parent.

So: I would also be for doing things like sizing inside the nested components personally so there's that flexibility there if there ever need to be more variations of the empty state + it's easier to read.

2022-05-13 12:24 UTC, taniya-atomlearning commented on src/components/empty-state/EmptyState.tsx
> +      xs: {
I have updated the component to use the cloneElement now

2022-05-13 12:26 UTC, taniya-atomlearning commented
@thomasdigby I have addressed the feedback. Just one thing snapshot test is failing in the build even though its passing locally. Have you seen this before?

2022-05-13 12:33 UTC, thomasdigby commented
> @thomasdigby I have addressed the feedback. Just one thing snapshot test is failing in the build even though its passing locally. Have you seen this before?

Thanks! I'll have a quick look at that now

2022-05-16 07:06 UTC, andoulla commented on src/components/empty-state/EmptyState.tsx
> +        throw new Error()
it is a small change but I think we should be passing an error message here. 
```suggestion
        throw new Error("Invalid child element in EmptyState")
```

or something similar

2022-05-16 07:07 UTC, andoulla approved these changes
Just one minor change but I think it is ready to go

2022-05-16 08:25 UTC, thomasdigby commented on src/components/empty-state/EmptyState.mdx
> +The message can include Title and/or Body and sometimes they appear together with an illustration and actionable buttons.
Do we have an example with an actionable button? I wonder if we should wither remove this copy (to make it easier to get this PR in) or introduce an `EmptyState.Action` component in this PR?

2022-05-16 08:29 UTC, thomasdigby commented on src/components/empty-state/EmptyState.tsx
> +        ].includes(child.type)
Could we try this rewrite to avoid invoking each component on every render? This has worked for our `ActionIcon` component (checking `child.type` against the component) and should be a touch more performant and readable.

```jsx
if (
  child.type === EmptyStateImage || 
  child.type === EmptyStateTitle || 
  child.type === EmptyStateBody
)
```

2022-05-16 08:31 UTC, thomasdigby commented on src/components/empty-state/EmptyStateImage.tsx
> +export const EmptyStateImage: React.FC<EmptyStateImage> = (props) => (
I think we can avoid this by exporting `StyledImage` as `EmptyStateImage` directly, e.g. `export const EmptyStateImage = styled(Image, {})`

2022-05-16 08:32 UTC, thomasdigby commented on types/custom.d.ts
> +
Can we remove this file?

2022-05-16 08:33 UTC, thomasdigby approved these changes
Just those minor changes then all good from me! 👍

2022-05-16 11:38 UTC, LimeWub commented on src/components/empty-state/EmptyState.mdx
> +The message can include Title and/or Body and sometimes they appear together with an illustration and actionable buttons.
EmptyState.Action is just any type of button afaik - should there be a component for action which does includes and exports Button?

I think the text here makes sense as it matches the design but the Button is not a new component really.

2022-05-16 11:40 UTC, thomasdigby commented on src/components/empty-state/EmptyState.mdx
> +The message can include Title and/or Body and sometimes they appear together with an illustration and actionable buttons.
We probably ought to make that consistent though right? e.g. `Button size="sm"` where relevant, like how we've handled the other components

2022-05-16 11:51 UTC, LimeWub commented on src/components/empty-state/EmptyState.mdx
> +The message can include Title and/or Body and sometimes they appear together with an illustration and actionable buttons.
Asked Miguel and he says no, they are just flexible. So I think we just leave this to implementation.

<img width="610" alt="Screenshot 2022-05-16 at 12 50 03" src="https://user-images.githubusercontent.com/6905473/168586372-e1083d70-78a0-4671-a2ee-cc5cdd061f18.png">

2022-05-16 11:54 UTC, LimeWub commented on src/components/empty-state/EmptyState.tsx
> +  alignItems: 'center',
Why would we wan't to default to a minimum size? I can ask Miguel about this but not sure I see the benefit. Is this still something we want to check about doing?

2022-05-16 12:29 UTC, thomasdigby commented on src/components/empty-state/EmptyState.tsx
> +  alignItems: 'center',
Just to provide a bit of breathing room and space around the message, to make it easier to understand in the context of the view, but that might be solved by just increasing the padding a touch instead. It's something we can patch if its a problem

2022-05-16 12:35 UTC, merged