fix: allow on change handler in radio button field
Atom-Learning/components pull request #330
Opened 2022-05-09 09:18 UTC by Marcdup1

### Description

`RadioButtonField` does not expose a way of knowing when the value changes, it thus requires `watching` the form field to know when the value changes and then doing something. This PR adds an optional `onValueChange(value: string)` prop that will get called when a value in the radio group gets changed, allowing the caller to do something with that value.

2022-05-09 09:51 UTC, hollg requested changes

2022-05-09 09:51 UTC, hollg commented on src/components/radio-button-field/RadioButtonField.mdx
> +<RadioButtonField onValueChange={(value) => doSomethingWith(value)} />
This can be simplified a little:
```suggestion
<RadioButtonField onValueChange={doSomethingWith} />
```

2022-05-09 09:51 UTC, hollg commented on src/components/radio-button-field/RadioButtonField.test.tsx
> +import { fireEvent, render, screen, waitFor } from '@testing-library/react'
I think we should prefer `userEvent` over `fireEvent`, since it's a more realistic simulation of what happens with real user events: https://testing-library.com/docs/user-event/intro/#difference-to-fireevent

2022-05-09 09:51 UTC, hollg commented on src/components/radio-button-field/RadioButtonField.tsx
> +              onValueChange?.(value)
Now that I'm looking at the code, I'm not sure I properly understand the distinction that we're drawing between `onChange` and `onValueChange` 🤔 

They're called in the same set of circumstances, right? So to me it seems more intuitive that the user of this component would just add more stuff to the `onChange` func.

You mentioned a bug were `onChange` gets called multiple times per click. If we solved that bug, would it remove the need for this new prop?

2022-05-09 10:13 UTC, Marcdup1 commented on src/components/radio-button-field/RadioButtonField.tsx
> +              onValueChange?.(value)
`onChange` comes from the `render` prop function of the `<Controller />` component - so it doesn't provide a way to expose the value to the user still.

>You mentioned a bug where onChange gets called multiple times per click.

This was pertaining to the `onClick` passed into `<RadioButtonField.Item onClick={onClick} />` however I don't find it intuitive to add an on click to each Item?

2022-05-09 10:14 UTC, Marcdup1 commented on src/components/radio-button-field/RadioButtonField.mdx
> +<RadioButtonField onValueChange={(value) => doSomethingWith(value)} />
Makes sense, updated it now.

2022-05-09 10:15 UTC, Marcdup1 commented on src/components/radio-button-field/RadioButtonField.test.tsx
> +import { fireEvent, render, screen, waitFor } from '@testing-library/react'
Oh, interesting! Thank you for that!

2022-05-09 10:22 UTC, hollg commented on src/components/radio-button-field/RadioButtonField.tsx
> +              onValueChange?.(value)
Oh, got it! I totally agree that this should be passed to the group rather than the individual item. Thanks for explaining!

2022-05-09 10:22 UTC, hollg approved these changes

2022-05-10 09:35 UTC, D7Torres approved these changes

2022-05-10 11:18 UTC, merged