fix: action icon sizes
Atom-Learning/components pull request #350
Opened 2022-06-23 16:09 UTC by kerryambt

From https://github.com/Atom-Learning/components/issues/295

### Description

Attempting to properly align our `ActionIcon` -> `Icon` sizing, specifically with the `simple` variant. Previously it had a ton of spacing and lg/xl sizes were far from that.

### Implementation

If the appearance is simple, pass the size directly down to Icon, unless the Icon itself has a size prop. Otherwise, we return an Icon one size smaller than the ActionIcon. 

I have also updated Icon and ActionIcon to have all four sizes defined, as they did not have this.

Finally, I updated every place in the DS where ActionIcons were used, in order to make sure they had the same output as before.

### Issues

This does pose an issue in that we'll have to audit core in order to not break things, but the more we put this off the worse this will become in terms of we'll just keep making tech debt. We have a ton of ActionIcons that have either overridden CSS or just strange styling, because this sizing has always not matched in the way it should.

I have another guild day to take next week and am happy to leave this unmerged until then, and spend the time auditing core in order to make sure all our ActionIcons retain their desired styles.

2022-06-24 06:26 UTC, andoulla approved these changes

2022-06-24 06:26 UTC, andoulla commented on src/components/action-icon/ActionIcon.tsx
> +              child.props.size && appearance === 'simple'
Maybe I'm confused but since we check the size and simple appearance here and return the size icon that is passed, then why do we need the same check within the getIcon on line 201

2022-06-24 06:26 UTC, andoulla commented on src/components/action-icon/ActionIcon.tsx
> +      sm: { size: '$2 ' },
I get this notification from Github about a TS error  on line 1
<img width="595" alt="image" src="https://user-images.githubusercontent.com/5703687/175474767-3ea87f12-3e31-4e6f-9503-f5d241d6a1d4.png">

2022-06-24 06:27 UTC, andoulla commented
> This does pose an issue in that we'll have to audit core in order to not break things, but the more we put this off the worse this will become in terms of we'll just keep making tech debt. We have a ton of ActionIcons that have either overridden CSS or just strange styling because this sizing has always not matched in the way it should.

@kerryambt I have a clean up PR with some Icons I replacing in core, happy to mark the ones I had to override the size with the same string comment to help make them more discoverable

2022-06-24 08:32 UTC, hollg commented
Have you seen this Jira ticket for a fix to `ActionIcon` styling? Just asking because I don't see a reference to it here and want to avoid any overlapping/conflicting work! https://atomlearningltd.atlassian.net/jira/software/projects/DS/boards/27?selectedIssue=DS-66

2022-06-24 09:12 UTC, kerryambt commented on src/components/action-icon/ActionIcon.tsx
> +              child.props.size && appearance === 'simple'
so we allow size specified on the icon (i.e. if they did something like `<ActionIcon size="md"><Icon size="lg"/></ActionIcon>`) to override the action icon size only when it's appearance simple. the check on line 201 is checking based on the size from the action icon, but in instances where we want to override we allow `child.props.size` to be used.

2022-06-24 09:12 UTC, kerryambt commented on src/components/action-icon/ActionIcon.tsx
> +      sm: { size: '$2 ' },
yeah I have fixed this just now, was a type error.

2022-06-24 09:15 UTC, kerryambt commented
@andoulla that would be really helpful! 

@hollg I'd never seen that board before, so no :o I will link this PR there now :)

2022-06-24 09:22 UTC, andoulla approved these changes

2022-06-24 10:21 UTC, thomasdigby commented
I'm not loving the icon to container size ratio for medium, can we reduce the size of the icon just a touch in that context? e.g. 1/2px reduced size

I guess we need to consider how that would work if it was used alongside the standard `Icon`s, would the size difference matter...?

2022-06-24 11:19 UTC, thomasdigby commented on src/components/date-input/DateInput.tsx
> +              size={size}
Shouldn't the size of the `ActionIcon` button container match up with the `Input`? Could we avoid the extra positioning CSS above by retaining some form of conditional logic here like we had before?

2022-06-24 11:33 UTC, MiguelGDLR commented on src/components/date-input/DateInput.tsx
> +              size={size}
Hi, I just found this issue because Kerry commented a similar task I created. Can you tag me when there are discussions about changes in any style? otherwise, I can not keep track of them so design (Figma components) will be inconsistent with development.

2022-06-27 11:53 UTC, kerryambt commented on src/components/date-input/DateInput.tsx
> +              size={size}
@thomasdigby I have updated this to use the conditional logic again :)

2022-06-27 11:56 UTC, kerryambt commented
> I'm not loving the icon to container size ratio for medium, can we reduce the size of the icon just a touch in that context? e.g. 1/2px reduced size
> 
> I guess we need to consider how that would work if it was used alongside the standard `Icon`s, would the size difference matter...?

@thomasdigby slightly tweaked the sizing to give a little more space on medium, I agree it looks better. I also realised I could simplify the conditional logic by using compound variants, so have changed up the code a bit.

2022-06-27 14:09 UTC, andoulla requested changes

2022-06-27 14:09 UTC, andoulla commented on src/components/action-icon/ActionIcon.tsx
> +      size = 'sm',
is it a good idea to change the default value of this? It will cause a bit of a pain in core to update all of the instances where md was assumed the default

2022-06-27 14:09 UTC, andoulla commented on src/components/icon/Icon.tsx
> +      xs: { size: '$1', strokeWidth: '1.75' },
we need to make this update a breaking change when we release it.  This change affects everything

2022-06-27 14:09 UTC, andoulla commented on src/components/icon/Icon.tsx
> +  ({ is: SVG, size = 'sm', ...remainingProps }, ref) => (
similar to above, I don't think we should change the default value as it will make the migration harder

2022-06-27 14:11 UTC, kerryambt commented on src/components/action-icon/ActionIcon.tsx
> +      size = 'sm',
the tokens had to change so they matched buttons. so what was md is now sm. changing the default value makes it less likely we need to change as many places.

2022-06-27 14:11 UTC, kerryambt commented on src/components/icon/Icon.tsx
> +  ({ is: SVG, size = 'sm', ...remainingProps }, ref) => (
as above :)

2022-06-27 14:34 UTC, andoulla commented on src/components/icon/Icon.tsx
> +      xs: { size: '$1', strokeWidth: '1.75' },
to do it you need to add a BREAKING_CHANGE in the commit message, as this is automatically released
<img width="833" alt="image" src="https://user-images.githubusercontent.com/5703687/175966411-d14955c5-0c75-405f-b5eb-7236f3ad421b.png">
https://design.atomlearning.technology/components/versioning

2022-06-27 14:35 UTC, kerryambt commented on src/components/icon/Icon.tsx
> +      xs: { size: '$1', strokeWidth: '1.75' },
thanks! saves me looking for that later :)

2022-06-28 08:59 UTC, thomasdigby commented
> > I'm not loving the icon to container size ratio for medium, can we reduce the size of the icon just a touch in that context? e.g. 1/2px reduced size
> > I guess we need to consider how that would work if it was used alongside the standard `Icon`s, would the size difference matter...?
> 
> @thomasdigby slightly tweaked the sizing to give a little more space on medium, I agree it looks better. I also realised I could simplify the conditional logic by using compound variants, so have changed up the code a bit.
> 
> ![image](https://user-images.githubusercontent.com/66493855/175935754-3fbe7794-0474-404f-9ea2-9ffeb5910c4a.png)



> > I'm not loving the icon to container size ratio for medium, can we reduce the size of the icon just a touch in that context? e.g. 1/2px reduced size
> > I guess we need to consider how that would work if it was used alongside the standard `Icon`s, would the size difference matter...?
> 
> @thomasdigby slightly tweaked the sizing to give a little more space on medium, I agree it looks better. I also realised I could simplify the conditional logic by using compound variants, so have changed up the code a bit.
> 
> ![image](https://user-images.githubusercontent.com/66493855/175935754-3fbe7794-0474-404f-9ea2-9ffeb5910c4a.png)

Great, thanks. Looks better now. Will take another look through this update today 👍

2022-06-28 09:33 UTC, LimeWub commented on src/components/action-icon/ActionIcon.mdx
> -    <Icon is={Clip} size="sm" />
Is there a reason we are removing the `size` prop here?
I kindddddd of don't like removing the explicit size prop. 
Like, I can see the default has changed but if the default ever changes again this will just be more things to add back to the code - plus, I don't really like depending on the defaults of the components for things controlled via props and think all props should be explicit.

2022-06-28 13:02 UTC, andoulla commented on src/components/action-icon/ActionIcon.mdx
> -    <Icon is={Clip} size="sm" />
I on the other hand find the defaults very handy. In my head, the default is the standard of what we should be using (sizes or themes etc) and it points out the intentionality of when we need to change from the default

2022-06-28 16:29 UTC, kerryambt commented on src/components/action-icon/ActionIcon.mdx
> -    <Icon is={Clip} size="sm" />
yeah I'm with @andoulla here - we want to assume certain things with the design system in order to allow fast iteration on ideas. not having defaults goes against that imo.

the size was removed here because it is now properly passed down from ActionIcon, so that Icons within ActionIcons are explicitly and consistently sized to the size of their ActionIcon.

I do see your point, and don't 100% disagree in that there's definitely merit to that line of thought, I just think it's not what we've decided the DS should be. Happy to open up more conversations on the matter but most of the decisions in this PR came from Miguel and I feel like at the end of the day DS owning designer has more weight in the choices the DS makes than developers :)

2022-06-28 18:51 UTC, LimeWub commented on src/components/action-icon/ActionIcon.mdx
> -    <Icon is={Clip} size="sm" />
Okay so, honestly, I (once again) hadn't noticed this was an `.mdx` rather than a `.tsx` file and thought it actually had impact to real components. (I thought it was the icon for the Accordion we were changing or something cause while scanning I combined the filename of this and the file above ;_;) - oops.

Ye, removing the prop doesn't matter on an `.mdx` file and passing the size down from the ActionIcon makes sense. 

My bad for flagging this.

2022-06-28 18:57 UTC, kerryambt commented on src/components/action-icon/ActionIcon.mdx
> -    <Icon is={Clip} size="sm" />
It's better to flag things and it be okay than not flag things! MDX files can be sneaky 😅

2022-06-29 14:54 UTC, kerryambt commented
@andoulla @thomasdigby @MiguelGDLR changes have been made that _finally_ have all of us on the same page. I've added breaking change tags as well. should be good to go now finally!

2022-06-29 15:52 UTC, thomasdigby commented
Thanks @kerryambt I'll review this evening!

2022-06-30 08:20 UTC, thomasdigby commented on src/components/action-icon/ActionIcon.mdx
> +    <Icon is={Clip} />
Sorry, this is a "while we're here", but can we remove the `appearance="subtle"` variants in the docs? That variant was removed a while ago so the docs are out of date

2022-06-30 08:27 UTC, thomasdigby commented on src/components/action-icon/ActionIcon.tsx
> +            isInActionIcon: !child.props.size,
Is there any way we can avoid this prop? I get the benefit of being explicit about the context and making styling decisions in `Icon` easier, but it feels like we're coupling the components a bit too much. I wonder if just a different name might help? Worth bearing in mind that this prop will be exposed via the props table in the docs

I also wonder if we can more explicit about converting the `child.props.size` here to a boolean, I didn't initially understand the logic here.

2022-06-30 08:30 UTC, thomasdigby commented on src/components/notification-badge/__snapshots__/NotificationBadge.test.tsx.snap
> +    width: var(--sizes-3);
Did we need to change the size prop in `NotificationBadge`? Seems like both `height`/`width` values are changing in this snapshot

2022-07-05 08:42 UTC, kerryambt commented on src/components/notification-badge/__snapshots__/NotificationBadge.test.tsx.snap
> +    width: var(--sizes-3);
it's just the icon used in the test. because it's size lg, which previously was using incorrect sizing, it's had all its value changed.

2022-07-05 08:56 UTC, kerryambt commented on src/components/action-icon/ActionIcon.tsx
> +            isInActionIcon: !child.props.size,
I think a different name might suffice, I think it's better than having a bunch of complicated logic to determine size solely on the action icon. maybe like `isWrapped` or `isInContainer`?

2022-07-06 08:00 UTC, thomasdigby commented
@andoulla @kerryambt I'm not against skipping the breaking change and just bumping it as a minor update. I want to get to a place where we're actually sticking to Semver soon, but we've done plenty of breaking changes previous to this without a major bump.

2022-07-06 13:37 UTC, thomasdigby commented on src/components/action-icon/ActionIcon.tsx
> +            isInActionIcon: !child.props.size,
Actually, I think it's fine as is, I don't think there's a need to decouple from `ActionIcon` when there's a clear dependency on it. 👍

2022-07-08 08:02 UTC, andoulla commented on lib/src/components/action-icon/ActionIcon.tsx
> +            isInActionIcon: !child.props.size,
I guess we could just say these are the sizes and don't override them (just like we do with button). Less flexibility sometimes means that it is easier to use the component

2022-07-08 08:05 UTC, andoulla approved these changes

2022-07-08 08:06 UTC, andoulla commented on lib/src/components/action-icon/ActionIcon.mdx
>    <Tooltip.Trigger>
I think this section is misleading. We have a TooltipActionIcon in core where we do just that. Maybe we either do @kerryambt idea where we just give the option to show a tooltip as a thing this component does or we move the TooltipAction icon here next to it, so people know it exists. 

@thomasdigby @hollg 


Obviously, this needs to be part of a follow-up and not here

2022-07-12 09:41 UTC, thomasdigby approved these changes

2022-08-01 11:18 UTC, LimeWub commented on lib/src/components/icon/Icon.tsx
> +      isInActionIcon: true,
Is there a reason why we are depending on `isInActionIcon` prop in `Icon` to do the sizing of this?

I don't think the `Icon` should even know if it's in ActionIcon - can we not target this - or just pass the right size from ActionIcon itself?

2022-08-11 15:58 UTC, kerryambt commented
@hollg @LimeWub following a conversation with Myrto I realised I could avoid compound variants _and_ conditional logic and use a simple map to size the Icon based on the ActionIcon size. This has the benefit of working with the new Icon stroke widths and removing the unnecessary compound variant CSS. Could you take a look when you get time? :)

2022-09-06 16:24 UTC, merged