Feat: Promo Banner (Regular)
Atom-Learning/components pull request #501
Opened 2023-04-19 09:00 UTC by avirati

https://atomlearningltd.atlassian.net/browse/DS-255
https://atomlearningltd.atlassian.net/browse/STU-1306

2023-04-19 10:28 UTC, LimeWub commented on lib/src/components/banner/BannerButton.tsx
> +  return appearance === 'outline' ? (
Do you need this ternary here? 
Doesn't passing in `appearance` just work (even when undefined?)

if not can we maybe just default the appearance to `solid` (or whatever the regular is)

2023-04-19 11:25 UTC, LimeWub commented on lib/src/components/banner/BannerActions.tsx
> +import invariant from 'invariant'
Is this a new thing we are introducing?

2023-04-19 11:25 UTC, LimeWub commented on lib/src/components/banner/BannerActions.tsx
> +          throw new Error(INVALID_CHILDREN_MESSAGE)
The message here actually doesn't say what it's really about.

2023-04-19 11:25 UTC, LimeWub commented on lib/src/components/banner/BannerActions.tsx
> +  invariant(
I don't think it's important to test this tbh - worst case scenario we get a third button in `outline` style...

And this test here isn't really checking just valid children anyway (if not valid element child or non-button it still counts it...)

2023-04-19 11:25 UTC, LimeWub commented on lib/src/components/banner/BannerImage.tsx
> +      <Box
Why not just use Image + object-fit/positioning? Rather than Box

2023-04-19 11:25 UTC, LimeWub commented on lib/src/components/banner/BannerRegular.tsx
> +        maxWidth: '736px'
Why maxWidth? and why 2 different ones... by 1 px?

2023-04-19 11:25 UTC, LimeWub commented on lib/src/components/banner/BannerRegular.tsx
> +        '&:not(:disabled)': {
Why does it matter if it's disabled?

2023-04-19 11:25 UTC, LimeWub commented on lib/src/components/banner/BannerRegular.tsx
> +        '&:not(:disabled)': {
Also come to think of it. Why would it even be disabled? I'm assuming if the banner is non-dismissible the cross will not be there?

2023-04-19 11:25 UTC, LimeWub commented on lib/src/components/banner/BannerRegular.tsx
> +      <Dismissible value="dismiss-banner-regular">
value should probably be a prop - so that implementation can catch the dismiss with something meaningful onDismiss - also onDismiss should be getting passed in to this since it's not benefiting from the `...rest`

2023-04-19 11:25 UTC, LimeWub commented on lib/src/components/banner/BannerRegular.tsx
> +          <ColorScheme {...colorScheme}>
Can you have the colourscheme be the outtermost element on this?

Just will be easier to remove if we ever just let CS be used as its own flexible wrapper component. Plus it can replace the wrapping Box for the position relative if you do actually need this on the box and it can't just go on `Dismissible` itself.

2023-04-19 11:25 UTC, LimeWub commented on lib/src/components/banner/BannerRegular.tsx
> +            <Container size={size} css={{ ...css }} {...props}>
css doesn't need spreading here and also doubt if that's where it would need to be passed in (?) Why does it need to be passed to the container?

2023-04-19 11:25 UTC, LimeWub commented on lib/src/components/banner/BannerText.tsx
> +  const color = resolveEmphasis('description', emphasis)
imo (very imo) it'd be clearer if you just had the variants explicitely in this file rather than having the resolveEmphasis helper.

it's like 6 lines and it's obfuscating it less.

2023-04-20 04:39 UTC, avirati commented on lib/src/components/banner/BannerButton.tsx
> +  return appearance === 'outline' ? (
You're right, removed the redundant code 👍

2023-04-20 04:41 UTC, avirati commented on lib/src/components/banner/BannerContent.tsx
> +        p: 'calc($4 + $2)',
Yep 💯

2023-04-20 04:44 UTC, avirati commented on lib/src/components/banner/BannerContent.tsx
> +        {heading}
Derived from our previous conversations, I thought the design itself wants us to restrict users from deviating from the design. Hence the added restrictions (to make sure things look good at any given time)

2023-04-20 04:44 UTC, avirati commented on lib/src/components/banner/BannerActions.tsx
> +import invariant from 'invariant'
It has been there since a quite some time and used in a couple of components

2023-04-20 04:48 UTC, avirati commented on lib/src/components/banner/BannerActions.tsx
> +          throw new Error(INVALID_CHILDREN_MESSAGE)
Good spot, fixed 👍

2023-04-20 04:50 UTC, avirati commented on lib/src/components/banner/BannerActions.tsx
> +  invariant(
The restrictions are in place as per the specs. Happy to discuss this further but I am in favour of putting restrictions as without it, we risk unintended use of the component

2023-04-20 04:52 UTC, avirati commented on lib/src/components/banner/BannerImage.tsx
> +      <Box
Personal preference, do you have any strong reasons for not using it ?

2023-04-20 04:53 UTC, avirati commented on lib/src/components/banner/BannerRegular.tsx
> +        maxWidth: '736px'
This is as per design document.
https://www.figma.com/file/KjgQh7eTwEfJmH6e56k9mX/DS-Documentation?node-id=10641-95059&t=R2hkXpCanUQTM1xn-4

2023-04-20 04:55 UTC, avirati commented on lib/src/components/banner/BannerRegular.tsx
> +        '&:not(:disabled)': {
This is done to avoid `!important`. Background passed here gets overridden by the component's css unless we provide a more specific selector (happy to use other alternative if you have a suggestion).

2023-04-20 04:59 UTC, avirati commented on lib/src/components/banner/BannerRegular.tsx
> +      <Dismissible value="dismiss-banner-regular">
Makes sense 👍

2023-04-20 05:02 UTC, avirati commented on lib/src/components/banner/BannerRegular.tsx
> +          <ColorScheme {...colorScheme}>
Yep, great suggestion !

2023-04-20 05:03 UTC, avirati commented on lib/src/components/banner/BannerRegular.tsx
> +            <Container size={size} css={{ ...css }} {...props}>
You're right, this is left over code that I forgot to remove 👍

2023-04-20 05:06 UTC, avirati commented on lib/src/components/banner/BannerText.tsx
> +  const color = resolveEmphasis('description', emphasis)
I don't agree with you on this. At present we have 3 elements and 3 emphasis, a total of 9 colours for different use cases. This will blow up exponentially if we throw in a couple more emphasis / elements. Having these in one place is the right call imo. Happy to discuss this further.

2023-04-20 07:39 UTC, andoulla commented on lib/src/components/banner/BannerActions.tsx
> +  invariant(
yes with Avi, the only restriction of this type we agreed for V1 was this one that they can have 0to 2 buttons

2023-04-20 07:39 UTC, andoulla commented on lib/src/components/banner/BannerActions.tsx
> +        // Override button appearance - make the second button outlined
This one we had agreed that don't need for V1 but since you did it lets not waste it

2023-04-20 07:39 UTC, andoulla commented on lib/src/components/banner/BannerActions.tsx
> +              { appearance: 'outline' }
for highContrast,  a button can be only neutral or primary is it ok to set it to outline here?

2023-04-20 07:39 UTC, andoulla commented on lib/src/components/banner/Banner.utils.ts
> +  hiContrast: {
can we use the full name, please? `highContrast`, `lowContrast`

2023-04-20 07:39 UTC, andoulla commented on lib/src/components/banner/BannerContent.tsx
> +      <Stack direction="column" css={{ pr: 'calc($5 + $4)' }}>
$5+$4 = 48px which we have a token ($7). can we use that, please?

2023-04-20 07:39 UTC, andoulla commented on lib/src/components/banner/BannerImage.tsx
> +      <Box
Actually, our image component has some extra features so it might be good to use it

2023-04-20 07:39 UTC, andoulla commented on lib/src/components/banner/BannerRegular.tsx
> +        maxWidth: '736px'
I think that might just be an oversight. I think we can use the same one. it is only a pixel nobody will notice

2023-04-20 07:43 UTC, avirati commented on lib/src/components/banner/BannerRegular.tsx
> +        maxWidth: '736px'
I'll confirm with @AtanasKovachev

2023-04-20 08:16 UTC, AtanasKovachev commented on lib/src/components/banner/BannerRegular.tsx
> +        maxWidth: '736px'
From my understanding, we decided not to go with different banner layouts for each breakpoint, but we still wanted to have the different layouts for desktop and mobile resolutions (one with the image on the side, one without). 

So that's how we defined the 'md' and 'sm' sizes of the banner - 'sm' is used only for resolutions below 736px (max-width of the banner on a 800px screen with 32px padding on each side, e.g. a typical dashboard layout) and 'md' is used only when the width is 737px + for a desktop layout. That ensures we'd never have the image-less mobile banner on a desktop layout and we'd never have the big desktop banner on a narrow mobile screen.

2023-04-20 13:42 UTC, MiguelGDLR commented on lib/src/components/banner/BannerActions.tsx
> +        gap: 'calc($4 + $1)'
Is this for the gap between buttons? I think it should be 16px ($4), we had it wrong in the docs sorry!
@AtanasKovachev correct me if I'm wrong

2023-04-21 04:32 UTC, avirati commented on lib/src/components/banner/BannerActions.tsx
> +        gap: 'calc($4 + $1)'
Updated to `$4`

2023-04-21 04:35 UTC, avirati commented on lib/src/components/banner/BannerActions.tsx
> +              { appearance: 'outline' }
`primary` button does not look good as it kind of mixes in with the background. This was done after discussing with @AtanasKovachev

2023-04-21 04:40 UTC, avirati commented on lib/src/components/banner/Banner.utils.ts
> +  hiContrast: {
Done 👍

2023-04-21 04:42 UTC, avirati commented on lib/src/components/banner/BannerContent.tsx
> +      <Stack direction="column" css={{ pr: 'calc($5 + $4)' }}>
Good catch. Updated.

2023-04-21 05:33 UTC, andoulla commented on lib/src/components/banner/BannerActions.tsx
> +              { appearance: 'outline' }
thanks for confirming

2023-04-21 05:34 UTC, andoulla approved these changes

2023-04-21 06:46 UTC, avirati commented on lib/src/components/banner/BannerImage.tsx
> +      <Box
Okay so I spent some time into this and came to a conclusion that using `img` without fixed sized parent container will not yield the desired results. Fixed size containers are not going to work because the banner is supposed to have a flexible height / width. Given such restrictions, if you have a way out, do let me know and I shall implement that. Until then, I am sticking with this approach ☝️ 

https://user-images.githubusercontent.com/1936119/233560774-88319fca-ee28-4f53-b438-5bb05863ad10.mov

2023-04-21 06:49 UTC, avirati commented on lib/src/components/banner/BannerRegular.tsx
> +        maxWidth: '736px'
I can them both `736px` if that helps. Since we are not using media query breakpoints, 1px difference can be avoided. Shall I proceed ?

2023-04-21 11:07 UTC, LimeWub reviewed
I want to pull this down in a bit to check some of my suggestions - went back to u for some of the things but would actually like to have a look at some things with the code running for a bit - soz for the delays.

2023-04-21 11:07 UTC, LimeWub commented on lib/src/components/banner/BannerRegular.tsx
> +        '&:not(:disabled)': {
Honestly, just do `!important` if you need to override something which the ActionIcon or whichever component can't do - and maybe flag in a DS ticket that we have this use case so we can look at the component which doesn't allow it properly separately.

2023-04-21 11:07 UTC, LimeWub commented on lib/src/components/banner/BannerRegular.tsx
> +const Dismiss = styled(ActionIcon, {
I'd be tempted to move this component to its own little file to keep this one short and just about the BannerRegular component.

2023-04-21 11:13 UTC, hollg commented on lib/src/components/banner/BannerContent.tsx
> +        {heading}
I think I'm lacking context on the previous conversations that Avi refers to, but @LimeWub is right about the principle we want to stick to; we can't effectively enforce design decisions through code and things get messy when we try.

Wherever possible, we want the low-level components to be flexible, accepting arbitrary `children` which allow the consumer to to compose the components together. There should be design review steps in place to make sure that we're not using this flexibility to break any design guidelines. We can then also add higher-level components that package the low-level components together into useful defaults that require less boilerplate to use, and are more opinionated. But generally when we've tried to make the low-level stuff opinionated, we end up needing breaking changes to APIs when the design guidelines inevitably change.

2023-04-21 11:29 UTC, D7Torres commented on lib/src/components/banner/BannerContent.tsx
> +        {heading}
I love restrictions in design, but I've not been here long enough
So, I've not seen this yet
> we can't effectively enforce design decisions through code and things get messy when we try.
but I believe you, and we agreed that we want to make components the way Gary and Myrto just described.

2023-04-24 04:06 UTC, avirati commented on lib/src/components/banner/BannerContent.tsx
> +        {heading}
Thanks for the insight, I understand your point.

@AtanasKovachev if we were to remove restrictions like suggested above, we would lose this padding. The developer would be required to make visual adjustments as required. Is this acceptable ?

<img width="703" alt="Screenshot 2023-04-24 at 05 05 16" src="https://user-images.githubusercontent.com/1936119/233897704-bf8f5d4b-6abc-4271-a950-98bc9fd02829.png">

2023-04-24 04:09 UTC, avirati commented on lib/src/components/banner/BannerActions.tsx
> +import invariant from 'invariant'
Docs here seem to suggest that `invariant` throws different kind of messages depending on `environment`. I'd say that it is slightly more sophisticated than usual `throw new Error(...)`.

2023-04-24 04:19 UTC, avirati commented on lib/src/components/banner/BannerRegular.tsx
> +        '&:not(:disabled)': {
Hmm, that would make it lose `:active` `:hover` `:focus` states unless I added css for that too. Too much of a hassle ?

2023-04-24 04:22 UTC, avirati commented on lib/src/components/banner/Banner.test.tsx
> +        dismissible={{
I did it to reduce number of props but sure, I can remove it

2023-04-24 04:33 UTC, avirati commented on lib/src/components/banner/Banner.test.tsx
> +        type="regular"
Redundant code. Removing 👍

2023-04-24 04:39 UTC, avirati commented on lib/src/components/banner/BannerActions.tsx
> +        '& > button': {
Good idea !

2023-04-24 05:13 UTC, avirati commented on lib/src/components/banner/BannerRegular.tsx
> +const Dismiss = styled(ActionIcon, {
Yep, sounds good 👍

2023-04-24 05:19 UTC, avirati commented on lib/src/components/banner/BannerContent.tsx
> +        {heading}
Removed restrictions. @AtanasKovachev please review the screenshots in PR description

2023-04-24 05:20 UTC, avirati commented on lib/src/components/banner/BannerRegular.tsx
> +        maxWidth: '736px'
Both are `736px` now.

2023-04-24 05:21 UTC, avirati commented on lib/src/components/banner/Banner.test.tsx
> +        dismissible={{
Removed. Please check the PR description for updated info

2023-04-24 05:21 UTC, avirati commented on lib/src/components/banner/BannerActions.tsx
> +        '& > button': {
Done

2023-04-24 05:23 UTC, avirati commented on lib/src/components/banner/BannerRegular.tsx
> +const Dismiss = styled(ActionIcon, {
Done

2023-04-25 12:08 UTC, andoulla commented on documentation/content/components.content.banner.md
> +
can we add a note that this component might also be referred to as Promo Banner? it will help bridge the terminology between design and tech

2023-04-25 12:10 UTC, andoulla requested changes

2023-04-25 12:10 UTC, andoulla commented on documentation/content/components.content.banner.md
> +      <ComponentProps component="BannerRegular" />
can we please make sure that we add the props for the sub components like in https://atomlearning.design/components/content/toggle-group

2023-04-25 18:39 UTC, LimeWub commented on documentation/content/components.content.banner.md
> +---
Could you copy/paste a bit in here about the use of ColorScheme in this component so its a bit more clear? 

ie. like the bit about CS in here: https://atomlearning.design/components/layout/accordion

2023-04-25 18:41 UTC, LimeWub commented on documentation/content/components.content.banner.md
> +---
I'd also name this file "Banner Regular" since there will be a separate one for "Banner Slim" but we can work on renames separately and it's okay for now since it's the only one.

2023-04-25 18:42 UTC, LimeWub commented on documentation/content/components.content.banner.md
> +
Are the designers okay with this rename to simple "Banner" btw? Have they been informed? 

If they have and they are cool with it, they should change the name in their Figma and then we don't need to bridge this between design and tech in this documentation here.

2023-04-26 04:26 UTC, avirati commented on documentation/content/components.content.banner.md
> +      <ComponentProps component="BannerRegular" />
I added the following - 

```jsx
      <ComponentProps component="BannerRegular" />

      <ComponentProps component="BannerRegular.Content" />

      <ComponentProps component="BannerRegular.Heading" />

      <ComponentProps component="BannerRegular.Text" />

      <ComponentProps component="BannerRegular.Actions" />

      <ComponentProps component="BannerRegular.Image" />

      <ComponentProps component="BannerRegular.Button" />

      <ComponentProps component="BannerRegular.Dismiss" />
```

The docs do not seem to generate the API details for any other component. I traced it to 

```typescript
const getComponentProps = (name) =>
  docgen
    .filter(Boolean)
    .find((component) => component.displayName === name || component.displayName === pascalcase(name))
```

Seems like the displayName does not match, please suggest if I should rename all the sub components (and displayName) as `BannerRegular*` instead of `Banner*` (Seems to work)

2023-04-26 04:38 UTC, avirati commented on documentation/content/components.content.banner.md
> +
@AtanasKovachev could you please review the documentation (PR description) ?

2023-04-26 04:38 UTC, avirati commented on documentation/content/components.content.banner.md
> +---
Done

2023-04-26 04:38 UTC, avirati commented on documentation/content/components.content.banner.md
> +---
Done

2023-04-26 04:40 UTC, avirati commented on documentation/content/components.content.banner.md
> +      ### Examples
Thanks, have brought it to the same level as 'Anatomy'. Will make note of the other changes for future reference 👍

2023-04-26 04:40 UTC, avirati commented on documentation/content/components.content.banner.md
> +      <CodeBlock live={false} preview={true} code={`
Done

2023-04-26 05:55 UTC, LimeWub commented on documentation/content/components.content.banner.md
> +      <ComponentProps component="BannerRegular" />
yep i'd do the rename

2023-04-26 06:12 UTC, avirati commented on documentation/content/components.content.banner.md
> +      <ComponentProps component="BannerRegular" />
Done ✅

2023-04-26 06:41 UTC, andoulla commented on lib/src/components/banner/BannerContainer.tsx
> +    size: {
```suggestion
// Designs available, need to be build in next iterations
    size: {
```

2023-04-26 06:42 UTC, andoulla approved these changes

2023-04-26 06:50 UTC, avirati commented on lib/src/components/banner/BannerContainer.tsx
> +    size: {
Discussed separately

2023-04-26 07:55 UTC, LimeWub approved these changes

2023-04-27 08:25 UTC, avirati commented on documentation/content/components.content.banner.md
> +
Discussed offline, all good

2023-04-27 08:26 UTC, merged