WIP: STU 1309 create pagination component
Atom-Learning/components pull request #523
Opened 2023-05-11 10:28 UTC by mzeenkala23

THIS IS WIP!!

2023-05-12 04:10 UTC, avirati commented on lib/src/components/pagination/PaginationNextButton.tsx
> +    }
```suggestion
    onClick?.(goToNextPage)
```

2023-05-12 04:12 UTC, avirati commented on lib/src/components/pagination/PaginationPages.tsx
> +  const isTruncated = numOfPages > 4
Shall we move this `4` to a constant ?

2023-05-12 04:13 UTC, avirati commented on lib/src/components/pagination/PaginationPages.tsx
> +      : listOfPages.slice(currentPage - 3, currentPage + 1)
This should be simplified

2023-05-12 04:15 UTC, avirati commented on lib/src/components/pagination/PaginationPreviousButton.tsx
> +    }
```suggestion
    onClick?.(goToPreviousPage)
```

2023-05-12 10:20 UTC, andoulla reviewed
I know this is not fixed but don't forget documentation is needed. Myrto can help you set up how to do it locally if you prefer and get stuck

2023-05-12 10:20 UTC, andoulla commented on lib/src/components/pagination/PaginationNextButton.tsx
> +      hasTooltip={false}
The ActionIcon is missing a label, which breaks accessibility rules. can you please add it and maybe add a way of overriding them if needed

2023-05-12 10:20 UTC, andoulla commented on lib/src/components/pagination/PaginationPageButton.tsx
> +  p: '0 !important',
Why so many !important?

2023-05-12 10:20 UTC, andoulla commented on lib/src/components/pagination/PaginationPageButton.tsx
> +      onClick={() => goToPage(pageNumber)}
Just thinking a bit ahead, we might want to pass extra stuff in the click action (like sending an event or an API call) it is good to follow the pattern from the next button where you have the option to do so

2023-05-12 10:20 UTC, andoulla commented on lib/src/components/pagination/PaginationPages.tsx
> +  const isTruncated = numOfPages > 4
+1

2023-05-12 10:20 UTC, andoulla commented on lib/src/components/pagination/PaginationPages.tsx
> +      : listOfPages.slice(currentPage - 3, currentPage + 1)
Also, if we have the const for the page as avi suggested then the 3 can become a derived value const -1

2023-05-12 10:20 UTC, andoulla commented on lib/src/components/pagination/PaginationPopover.tsx
> +            css={{ bg: '$white !important' }}
what is causing us having to overwrite the bg? could we create a variant with in this component to have a white version and the default version?

2023-05-12 10:20 UTC, andoulla commented on lib/src/components/pagination/PaginationPreviousButton.tsx
> +      hasTooltip={false}
same here

2023-05-14 14:25 UTC, mzeenkala23 commented on lib/src/components/pagination/PaginationNextButton.tsx
> +    }
I was meant to do `return  onClick(goToNextPage)` if we have an onClick so what if I do this instead

`
 const handleClick = () => {
    if (onClick) {
      return onClick(goToPreviousPage)
    }
    goToPreviousPage?.()
  }
`

2023-05-14 14:27 UTC, mzeenkala23 commented on lib/src/components/pagination/PaginationPageButton.tsx
> +  p: '0 !important',
This was the only way I could override the existing styles

2023-05-14 14:28 UTC, mzeenkala23 commented on lib/src/components/pagination/PaginationPopover.tsx
> +            css={{ bg: '$white !important' }}
Yeah variant seems like a good option will do this

2023-05-15 03:58 UTC, avirati commented on lib/src/components/pagination/PaginationNextButton.tsx
> +    }
Sounds good.

2023-05-18 08:00 UTC, mzeenkala23 commented on lib/src/components/pagination/PaginationPages.tsx
> +      : listOfPages.slice(currentPage - 3, currentPage + 1)
sounds good

2023-05-18 08:02 UTC, mzeenkala23 commented on lib/src/components/pagination/PaginationNextButton.tsx
> +      hasTooltip={false}
sure thing

2023-05-18 08:02 UTC, mzeenkala23 commented on lib/src/components/pagination/PaginationPreviousButton.tsx
> +      hasTooltip={false}
will had a label we can override

2023-05-18 09:23 UTC, andoulla requested changes

2023-05-18 09:23 UTC, andoulla commented on documentation/content/components.navigation.pagination.md
> +    `Pagination.PreviousButton` represents the backwards navigation element. It has a default label of `Previous page` but it can also receive a `label` prop to override the default one. It can recei
```suggestion
    `Pagination.PreviousButton` represents the backwards navigation element. It has a default label of `Previous page` but it can also receive a `label` prop to override the default one.  This is important for providing translated strings to the component.
    It can receive an `onClick` prop to override its default behaviour in case some logic or validation needs to be applied before going to the next page. It is automatically disabled while the user is viewing the first page.

```

2023-05-18 09:23 UTC, andoulla commented on documentation/content/components.navigation.pagination.md
> +    `Pagination.NextButton` represents the forwards navigation element. It has a default label of `Next page` but it can also receive a `label` prop to override the default one. It can receive an onC
same as above

2023-05-18 09:23 UTC, andoulla commented on documentation/content/components.navigation.pagination.md
> +    Below is an example of passing in a number to the `numOfPages` prop that will render 6 pages the `numOfElements` prop is set to 8 by default. So the user will see two navigation buttons, an actio
I would suggest moving these examples to where you explain what they do, above

2023-05-18 09:23 UTC, andoulla commented on documentation/content/components.navigation.pagination.md
> +
I would put some headers for each section to make it a bit more easy to scan

2023-05-18 09:23 UTC, andoulla commented on lib/src/components/pagination/Pagination.test.tsx
> +      mockTestQuestions={mockTestQuestions}
As we discussed before, we shouldn't call this mockTestQuestions. We need a generic name for this feature. This is the DS and we shouldn't tie this with domain-specific terminology. Because we might use this feature anywhere, outside the scope of mock tests, ie practices, or to render any set  of objects that have a completed/pending state (think instructions)

2023-05-18 09:23 UTC, andoulla commented on lib/src/components/pagination/Pagination.test.tsx
> +    // we need a way to get the current page
Will something like this work it("doesn't allow navigating out of the bullets range when no onComplete is passed", () => {
    render(
      <Stepper allowSkip stepCount={3} onStepChange={jest.fn()}>
        <Stepper.StepBack label={() => 'Back'} />
        <Stepper.Steps />
        <Stepper.StepForward label={() => 'Next'} />
      </Stepper>
    )
    fireEvent.click(screen.getByText('Next'))
    expect(screen.getByLabelText('step 2')).toHaveAttribute(
      'aria-current',
      'step'
    )

    fireEvent.click(screen.getByText('Next'))
    expect(screen.getByLabelText('step 3')).toHaveAttribute(
      'aria-current',
      'step'
    )

    fireEvent.click(screen.getByText('Next'))
    expect(screen.getByLabelText('step 3')).toHaveAttribute(
      'aria-current',
      'step'
    )
  })

2023-05-18 09:23 UTC, andoulla commented on lib/src/components/pagination/Pagination.tsx
> +  numOfElements = 8,
since this can only be either 8 or 6 by design why not restrict it? I know TS will throw a warning but we do have places we will use without TS and people will be able to pass anything down will probably break some of this internal logic

2023-05-18 09:23 UTC, andoulla commented on lib/src/components/pagination/PaginationNextButton.tsx
> +    isMockTestVariant,
I don't think we need this prop to be passed down. We can determine if it is this variant by checking if the array is passed down or not

2023-05-18 09:23 UTC, andoulla commented on lib/src/components/pagination/PaginationPageButton.tsx
> +        color: '$accent9 !important',
do we still need the important here?

2023-05-18 09:23 UTC, andoulla commented on lib/src/components/pagination/PaginationPageButton.tsx
> +      onClick={() => goToPage(pageNumber)}
maybe, do you see any problems with that

2023-05-18 09:23 UTC, andoulla commented on lib/src/components/pagination/PaginationPages.tsx
> +  const isMaxNumOfEl = numOfElements === 8
This is a reusable value which we need in the other component too, why not separate it out (the 8 or 6). 

Also, won't this cause a bug as-is because the numOfElements can be 6?

2023-05-18 09:23 UTC, andoulla commented on lib/src/components/pagination/PaginationPages.tsx
> +    return listOfPages.slice(0, isMaxNumOfEl ? 4 : 2)
do you mind adding a couple of small comments to explain what happens here, to ease the readability for the next person extending the component

2023-05-18 09:23 UTC, andoulla commented on lib/src/components/pagination/PaginationPages.tsx
> +  const lastMockTestQuestion = isMockTestVariant && mockTestQuestions.slice(-1)
Same comment as above, let's remove mockTest references in the names as it is domain-specific.  we can treat these as objects or pages

2023-05-18 09:23 UTC, andoulla commented on lib/src/components/pagination/PaginationPopover.tsx
> +          aria-label="trigger"
this is read out to users by a screen reader. Trigger doesn't mean anything. This should describe the action that happens when the user clicks it

2023-05-18 10:36 UTC, mzeenkala23 commented on lib/src/components/pagination/PaginationPageButton.tsx
> +      onClick={() => goToPage(pageNumber)}
nope, will make the change

2023-05-18 10:37 UTC, mzeenkala23 commented on lib/src/components/pagination/Pagination.test.tsx
> +    // we need a way to get the current page
ahh this is great, this might just work will try

2023-05-18 10:39 UTC, mzeenkala23 commented on lib/src/components/pagination/Pagination.test.tsx
> +      mockTestQuestions={mockTestQuestions}
hmm true, maybe `pages` would work i guess, then we can pass in an array of objects

2023-05-18 10:40 UTC, mzeenkala23 commented on lib/src/components/pagination/Pagination.tsx
> +  numOfElements = 8,
ok I guess I can add a check in this component that if its not 8 or 6 we throw an error?

2023-05-18 10:41 UTC, mzeenkala23 commented on lib/src/components/pagination/PaginationPages.tsx
> +    return listOfPages.slice(0, isMaxNumOfEl ? 4 : 2)
sure thing

2023-05-18 10:42 UTC, mzeenkala23 commented on lib/src/components/pagination/PaginationPages.tsx
> +  const lastMockTestQuestion = isMockTestVariant && mockTestQuestions.slice(-1)
yeah pages sounds like a good idea

2023-05-18 10:43 UTC, mzeenkala23 commented on lib/src/components/pagination/PaginationPopover.tsx
> +          aria-label="trigger"
will update it, with a better label

2023-05-18 10:47 UTC, mzeenkala23 commented on lib/src/components/pagination/PaginationPages.tsx
> +  const isMaxNumOfEl = numOfElements === 8
separate out as in make them constants? 

No this woudn't cause bugs when `numOfElements` is 6, the point of doing that check is so we know how much of the array we wish to slice off, for example when `numOfElements` is 8 we want to render more elements to the user hence we need to slice more of the array, hope that makes sense

2023-05-18 11:54 UTC, MiguelGDLR commented on lib/src/components/pagination/Pagination.tsx
> +  numOfElements = 8,
hey, regarding this, when I designed it, I was not 100% sure. So I don't want to limit us too much. 
I was thinking as a recommendation to put 2 options: maximun of 6 elements for mobile or small sections and 8 for desktop. But if leaving it customisable or something else makes it easier lets go with that.

2023-05-18 12:36 UTC, andoulla commented on lib/src/components/pagination/Pagination.tsx
> +  numOfElements = 8,
I think leaving customizable could cause edge cases lots of edge cases that will cause unexpected behaviours
what happens if someone passes a value less than 3
what happens if someone passes a value less that 4

In this count, we include the ellipsis and the next and previous buttons.

2023-05-18 12:42 UTC, andoulla commented on lib/src/components/pagination/PaginationPopover.tsx
> +          label="trigger"
a label in the action icon is the aria-label so same issue. you need to pass proper copy here

2023-05-18 13:01 UTC, mzeenkala23 commented on lib/src/components/pagination/Pagination.tsx
> +  numOfElements = 8,
Hey @MiguelGDLR  I was under the assumption  that we wanted to specifically render 6 0r 8 elements, so if we do pass in a value but its not 6 or 8 what happens at the moment is that we throw an error

2023-05-18 13:27 UTC, mzeenkala23 commented on lib/src/components/pagination/PaginationNextButton.tsx
> +    isMockTestVariant,
hmm but then won't be just be duplicating logic, we already do a check to see if it is a `isMockTestVariant` in the provider and expose it

2023-05-18 13:33 UTC, andoulla commented on lib/src/components/pagination/PaginationNextButton.tsx
> +    isMockTestVariant,
why do we need to do that in the provider?

2023-05-18 16:00 UTC, LimeWub commented
Hey, I can see that this is still Draft so I'm not reviewing properly yet but I can see the structure is fairly different to what I had proposed [in JIRA here ](https://atomlearningltd.atlassian.net/jira/software/projects/DS/boards/27?selectedIssue=DS-289)- so I just want to make sure this has been read?

2023-05-18 16:14 UTC, mzeenkala23 commented on lib/src/components/pagination/PaginationNextButton.tsx
> +    isMockTestVariant,
as the this check is being done in multiple different places, but typescript has been complaining so I have done it the way you have suggested

2023-05-18 23:16 UTC, mzeenkala23 commented on documentation/content/components.navigation.pagination.md
> +    The `Pagination` component comes with 3 components that combine to make the Pagination. The parent Pagination contains Pagination.PreviousButton, Pagination.Pages, Pagination.NextButton component
will make the change

2023-05-18 23:16 UTC, mzeenkala23 commented on documentation/content/components.navigation.pagination.md
> +    The `Pagination` component also takes in a `colorScheme` object to customise the colours of the component. ColorScheme is experimental and has been implemented only locally but you can read more
update

2023-05-18 23:16 UTC, mzeenkala23 commented on documentation/content/components.navigation.pagination.md
> +    The root `Pagination` component also allows the user to pass in a `numOfPages` prop which is a number that tells the component how many pages to render, or it can take in a `mockTestQuestions` pr
update here also

2023-05-18 23:16 UTC, mzeenkala23 commented on documentation/content/components.navigation.pagination.md
> +    `Pagination.PreviousButton` represents the backwards navigation element. It has a default label of `Previous page` but it can also receive a `label` prop to override the default one. It can recei
updated

2023-05-18 23:17 UTC, mzeenkala23 commented on lib/src/components/pagination/PaginationPopover.tsx
> +          label="trigger"
will update

2023-05-18 23:19 UTC, mzeenkala23 commented on documentation/content/components.navigation.pagination.md
> +
sure thing

2023-05-18 23:19 UTC, mzeenkala23 commented on documentation/content/components.navigation.pagination.md
> +    Below is an example of passing in a number to the `numOfPages` prop that will render 6 pages the `numOfElements` prop is set to 8 by default. So the user will see two navigation buttons, an actio
will update

2023-05-18 23:19 UTC, mzeenkala23 commented on documentation/content/components.navigation.pagination.md
> +    `Pagination.NextButton` represents the forwards navigation element. It has a default label of `Next page` but it can also receive a `label` prop to override the default one. It can receive an onC
updated

2023-05-19 07:42 UTC, andoulla commented on lib/src/components/pagination/Pagination.test.tsx
> +  { pageNumber: 7, isCompleted: true, isDisabled: true }
very minor but I would  do this instead:
```
{ pageNumber: 6, isCompleted: true },
  { pageNumber: 7, isCompleted: false, isDisabled: true }	 
```

The reason is that you are asserting 2 use cases in one, and it should be separated.
one object for the completed and one for the  disabled

2023-05-19 07:42 UTC, andoulla commented on lib/src/components/pagination/PaginationPages.tsx
> +          isEnrichedPages
why not call it what it is? this prop allows for  the whole list of pages to be shown so

`showExpandablePageList` or `showAllPagesList` or`showPopup` will be more meaningful to someone using this for the first time than isEnrichedPages

2023-05-19 08:39 UTC, mzeenkala23 commented on lib/src/components/pagination/pagination-context/PaginationContext.tsx
> +  const isMockTestVariant = Boolean(mockTestQuestions?.length)
updated code here too

2023-05-19 12:38 UTC, mzeenkala23 commented on lib/src/components/pagination/PaginationPages.tsx
> +          isEnrichedPages
Hey @andoulla  are you talking about `isEnrichedPages`?  if so this value is not used to show the whole list of pages, it is used to distinguish if we are dealing with a an array of objects that has properties such is pageNumber, isCompleted, isDisabled. Compared to the other array which is just an array of numbers.

2023-05-19 12:39 UTC, andoulla commented on lib/src/components/pagination/PaginationPages.tsx
> +          isEnrichedPages
it really confused me when reviewing it. We kind of need a better name let me think about it

2023-05-19 13:36 UTC, mzeenkala23 commented on lib/src/components/pagination/PaginationPages.tsx
> +          isEnrichedPages
Maybe I all pages can have the default structure of [{questionNumber: <number>}}] then if the dev user wishes to add
isCompleted or isDisabled properties they can do so. This way we may not need `isEnrichedPages` check anymore

2023-05-21 20:53 UTC, mzeenkala23 commented on lib/src/components/pagination/Pagination.test.tsx
> +  { pageNumber: 7, isCompleted: true, isDisabled: true }
good point will, change

2023-05-21 20:57 UTC, mzeenkala23 commented on lib/src/components/pagination/PaginationPages.tsx
> +          isEnrichedPages
as discussed  will rename the `pageCount` prop to `pages` a prop that can take a number dictating how many page items to render, this number will be transformed into an array of objects that have the default structure which looks like `{pageNumber: 1}`, or the prop can also take in a array of objects that can look like `{pageNumber: 1, isCompleted: false, isDisabled: false}`, where the `isCompleted and isDisabled` properties are optional

2023-05-22 17:13 UTC, Mhoog commented on lib/src/components/pagination/Pagination.tsx
> +    )
I'm not sure if we should throw an error here, I think there are 'friendlier' solutions to the problem. Could we just set `visibleElementsCount` to `6` or `8` in case the value is not one of those two?

Either way, the types already indicate that the value should be `6` or `8`. So if we receive another value here, the type errors are ignored during implementation. What would happen if we pass in another error, does it break completely?

2023-05-22 17:23 UTC, Mhoog commented on lib/src/components/pagination/types.ts
> +}
You could inherit some types:

```ts
export type PaginationProps = React.ComponentProps<typeof Box> & PaginationProviderProps & {
  colorScheme?: TcolorScheme
}
```

I'm not sure if we have standards for this, but I like to include the prop-type definitions for a component inside the component file, just so that you can quickly see and change things as you're working on it.

2023-05-22 17:23 UTC, Mhoog commented on lib/src/components/pagination/types.ts
> +export type visibleElementsCount = 6 | 8
```suggestion
export type VisibleElementsCount = 6 | 8
```

2023-05-22 17:25 UTC, Mhoog commented on lib/src/components/pagination/pagination-context/PaginationContext.tsx
> +  )
What is the reason for using `useMemo` here?

2023-05-22 17:27 UTC, Mhoog commented on lib/src/components/pagination/types.ts
> +export type Context = {
```suggestion
export interface PaginationContext {
```

2023-05-22 17:56 UTC, Mhoog commented on lib/src/components/pagination/PaginationPages.tsx
> +    : copyOfPages
I think you don't need the `pages` object at all and can use the util function in combination with `pagesCount` to generate an array instead:

```ts
const numOfPaginationItemsToRender = (currentPage, pagesCount, visibleElementsCount) => {
  const listOfPages = Array.from(
    { length: pagesCount }, 
    (value, index) => index + 1 // I don't think you need `{ pageNumber: x }`, you can just use numbers in the array.
  )
  
  if (pagesCount <= TRUNCATED_TRESHOLD) return listOfPages

  ...
}

const paginationItems = numOfPaginationItemsToRender(currentPage, pagesCount, visibleElementsCount)

2023-05-22 18:02 UTC, Mhoog commented on lib/src/components/pagination/PaginationItem.tsx
> +    color: '$grey900 !important'
Why do we need the `!important`s here?

2023-05-22 18:06 UTC, Mhoog commented on lib/src/components/pagination/PaginationItem.tsx
> +  const isPaginationItemDisabled = Boolean(disabledPages?.includes(pageNumber))
If you set the types for `indicatedPages` and `disabledPages` to required, and add a fallback to an empty array, you can remove the `Boolean()`.

Since they're also only used once, it's fine to move them inside the render function:
```jsx
return
  <StyledButton
    disabled={disabledPages.includes(pageNumber)}
    ...
  />
)
```

2023-05-22 18:09 UTC, Mhoog commented on lib/src/components/pagination/PaginationItem.tsx
> +  }
```suggestion
  const handleClick = () => {
    goToPage(pageNumber)
    onClick?.(pageNumber)
  }
```

2023-05-22 18:10 UTC, Mhoog commented on lib/src/components/pagination/PaginationItem.tsx
> +  }
Does this mean that the `bg` only changes if the `Dot` is hovered/focused? Is that the intended behaviour, or should it change when the button is hovered/focused?

2023-05-22 18:11 UTC, Mhoog commented on lib/src/components/pagination/PaginationItem.tsx
> +    popover: {
```suggestion
    isPopoverButton: {
```

2023-05-23 06:52 UTC, andoulla commented on lib/src/components/pagination/Pagination.test.tsx
> +      <PaginationComponent pages={6} onSelectedPageChange={pageChangeSpy} />
Isn't numOfPages renamed to pageCount?

2023-05-23 06:52 UTC, andoulla commented on lib/src/components/pagination/Pagination.test.tsx
> +      "The Pagination Component requires the 'pagesCount' prop it can be a numerical value above 0"
```suggestion
      "The Pagination Component requires the 'pagesCount' prop, it can be a numerical value above 0"
```

2023-05-23 06:52 UTC, andoulla commented on lib/src/components/pagination/Pagination.tsx
> +  }
+1, a good example will be in if there is a search and they can't find what they search. It will be 0 but it shouldn't crash the page

2023-05-23 06:52 UTC, andoulla commented on lib/src/components/pagination/PaginationItem.tsx
> +  const isPaginationItemDisabled = Boolean(disabledPages?.includes(pageNumber))
maybe it is a personal taste thing but I like that the consts are initialised here as it makes it very easy to read

2023-05-23 06:52 UTC, andoulla commented on lib/src/components/pagination/pagination-context/PaginationContext.tsx
> +  visibleElementsCount: 8,
shouldn't this be 6 as that's the default? also why not use the constant `RENDER_SIX_ELEMENTS`

2023-05-23 08:53 UTC, mzeenkala23 commented on lib/src/components/pagination/pagination-context/PaginationContext.tsx
> +  visibleElementsCount: 8,
ahhh yes great spot will update

2023-05-23 08:58 UTC, mzeenkala23 commented on lib/src/components/pagination/Pagination.test.tsx
> +      <PaginationComponent pages={6} onSelectedPageChange={pageChangeSpy} />
yeah so `PaginationComponent` is just a wrapper component used to render the actual pagination which does have the prop name `PageCount` but I can update the wrapper component prop name too, for consistency

2023-05-23 09:14 UTC, mzeenkala23 commented on lib/src/components/pagination/Pagination.tsx
> +  }
sounds good I will remove the error and just return null instead

2023-05-23 09:41 UTC, mzeenkala23 commented on lib/src/components/pagination/Pagination.tsx
> +    )
so it seems if we pass in any other number besides `6` or `8` it still works and just defaults to rendering 6 elements, so essentially it acts like the `visibleElementsCount` prop was not  is passed in. So as this is the case is it just enough to just remove the conditional?

2023-05-23 09:50 UTC, mzeenkala23 commented on lib/src/components/pagination/types.ts
> +}
nice this looks good, will change

2023-05-23 10:05 UTC, mzeenkala23 commented on lib/src/components/pagination/pagination-context/PaginationContext.tsx
> +  )
This was to prevent the recreation of pages everytime the component re-renders, is this not needed?

2023-05-23 10:11 UTC, mzeenkala23 commented on lib/src/components/pagination/PaginationPages.tsx
> +      <PaginationItem pageNumber={lastPageNumber} onClick={onClick} />
good point will change this too

2023-05-23 10:11 UTC, mzeenkala23 commented on lib/src/components/pagination/PaginationItem.tsx
> +    color: '$grey900 !important'
yeah this was a bit annoying I wasn't able to get the styling to work without the `!important`s

2023-05-23 10:25 UTC, avirati commented on lib/src/components/pagination/Pagination.test.tsx
Can we also add a test which makes sure that visible elements are expected values when we click "Next" / "Previous" multiple times. for example : 

< 1 | 2 | 3 | 4 | ... | 100 >

Click next 3 times

expect 4,5,6,7 to be visible

< 4 | 5 | 6 | 7 | ... | 100 >

and so on, when we click previous button

2023-05-23 10:31 UTC, mzeenkala23 commented on lib/src/components/pagination/PaginationItem.tsx
> +  }
ahh good spot, its meant to change colour when the button is hovered/focused will make the change

2023-05-23 10:33 UTC, avirati commented on lib/src/components/pagination/types.ts
Your types / interfaces have a lot of duplications. Try and declare a base type / interface and then extend that to create new ones. You'll face issues with duplication if you had to change any prop / type.

2023-05-23 10:34 UTC, avirati commented on lib/src/components/pagination/Pagination.tsx
> +  visibleElementsCount = 6,
You can omit this magic number and use `RENDER_SIX_ELEMENTS` instead. Please apply that to all places where you have used `6` or `8`

2023-05-23 10:38 UTC, avirati commented on lib/src/components/pagination/pagination-context/PaginationContext.tsx
> +export const usePagination = (): Context => {
Shall we move the hook to a separate file ?

2023-05-23 10:38 UTC, mzeenkala23 commented on lib/src/components/pagination/PaginationItem.tsx
> +    popover: {
better naming will update

2023-05-23 10:39 UTC, avirati commented on lib/src/components/pagination/PaginationPages.tsx
> +const TRUNCATED_THRESHOLD = 4
Let's move this to constants file

2023-05-23 10:39 UTC, avirati commented on lib/src/components/pagination/types.ts
> +export type pages = {
```suggestion
export type TPages = {
```

2023-05-23 10:40 UTC, avirati commented on lib/src/components/pagination/types.ts
> +export type visibleElementsCount = 6 | 8
Also, prefix with `T`

2023-05-23 10:40 UTC, avirati commented on lib/src/components/pagination/types.ts
> +export interface PaginationProps {
Please apply this to other places as well

2023-05-23 10:45 UTC, avirati commented on lib/src/components/pagination/PaginationPages.tsx
> +const numOfPaginationItemsToRender = (
This should be moved to a util file and unit tested against different values

2023-05-23 10:47 UTC, avirati commented on lib/src/components/pagination/PaginationNextButton.tsx
> +  const isNumber = typeof pages === 'number'
Is this still needed ?

2023-05-23 10:49 UTC, avirati commented on lib/src/components/pagination/PaginationItem.tsx
> +  size: '4px',
Do we not have DS tokens for this ?

2023-05-23 10:52 UTC, avirati commented on lib/src/components/pagination/PaginationItem.tsx
> +  }
@Mhoog that would execute both `goToPage` and `onClick`. Is that the expected behaviour ? @mzeenkala23 's implementation gives preference to `onClick` over `goToPage`.

2023-05-23 10:53 UTC, avirati commented on lib/src/components/pagination/Pagination.tsx
> +import { PaginationProps } from './types'
```suggestion
import type { PaginationProps } from './types'
```

Please apply this if applicable elsewhere.

2023-05-23 11:02 UTC, mzeenkala23 commented on lib/src/components/pagination/types.ts
Yeah good point will create a base type

2023-05-23 11:07 UTC, mzeenkala23 commented on lib/src/components/pagination/Pagination.tsx
> +  visibleElementsCount = 6,
ahh yes will update

2023-05-23 11:11 UTC, mzeenkala23 commented on lib/src/components/pagination/PaginationPages.tsx
> +const TRUNCATED_THRESHOLD = 4
sure thing

2023-05-23 11:12 UTC, mzeenkala23 commented on lib/src/components/pagination/types.ts
> +export type pages = {
good spot will update in other places too

2023-05-23 11:12 UTC, mzeenkala23 commented on lib/src/components/pagination/PaginationNextButton.tsx
> +  const isNumber = typeof pages === 'number'
will remove this

2023-05-23 11:13 UTC, mzeenkala23 commented on lib/src/components/pagination/PaginationItem.tsx
> +  size: '4px',
hmm doesn't look like it https://atomlearning.design/theme/overview/layout-and-space

2023-05-23 11:14 UTC, mzeenkala23 commented on lib/src/components/pagination/Pagination.tsx
> +import { PaginationProps } from './types'
yeah will update here and everywhere else

2023-05-23 11:50 UTC, LimeWub commented on lib/src/components/pagination/PaginationItem.tsx
> +      popover={isPopoverButton}
Does the `isPopoverButton` just change CSS? Does it not add functionality?
Could the `PopoverButton` variation be moved to its own file or the PaginationPopover file?
`PaginationPopoverItem` or similar? Would probably keep this file a bit more simple and it'll be easier to edit separately in the future.
(It can still use `PaginationItem` internally but it will be adding its own styles and any extra functionality in its own file instead)

2023-05-23 11:50 UTC, LimeWub commented on lib/src/components/pagination/PaginationItem.tsx
> +      aria-disabled={isPaginationItemDisabled}
I'm not sure it should need `aria-disabled` when you are using the html `disabled` prop.
Do the buttons get the `disabled` attribute on them correctly when disabled?

2023-05-23 11:50 UTC, LimeWub commented on lib/src/components/pagination/PaginationNextButton.tsx
> +  const isNumber = typeof pages === 'number'
`pages`? not `pageCount`? and pages might not be 'number'?
Can you have a look in this file to make sure it is using the correct props since the renames? I don't think this check should even be needed.

Update: Actually just noticed the pages thing in the context - I don't think you really need that. Just use the `pageCount` number

2023-05-23 11:50 UTC, LimeWub commented on lib/src/components/pagination/PaginationPages.tsx
> +    <Flex css={{ gap: '$1' }}>
We can't use `gap` on flex due to browser support (yes it's annoying). Can you please try using `<Stack gap={1} />` instead?

2023-05-23 11:50 UTC, LimeWub commented on lib/src/components/pagination/PaginationPages.tsx
> +const numOfPaginationItemsToRender = (
ngl this feel overly complicated - it's a difficult problem to solve. I do wonder if u replace the pages list with a number if it would be easier to read....

Also I wonder if there's a way to not use the values of 8 or 6 explicitely here and just use the passed in `visibleElementCount` instead and do it programmatically...

2023-05-23 11:50 UTC, LimeWub commented on lib/src/components/pagination/PaginationPopover.tsx
> +              isPopoverButton={true}
Oh I just noticed it is actually separated already! Can you maybe just move the `isPopoverButton` styles that `PaginationItem` uses in here and just use the styled version: `StyledPaginationItemPopover`? I think it'll be simpler to keep all the popover relevant things together.

2023-05-23 11:50 UTC, LimeWub commented on lib/src/components/pagination/PaginationPopover.tsx
> +          label="Open popover pagination"
This label here isn't accepting in a `translation`. I think it'd be better if you had a `copy` object for all the potential translations and just pull this one out from there as needed. (and cover prev/next in there too)

2023-05-23 11:50 UTC, LimeWub commented on lib/src/components/pagination/PaginationPopover.tsx
> +          data-testid="popover_trigger"
I'm concerned this may confuse some other test as it's too generic. Lets not have test-ids here and just add them in your jest test intead. Maybe you will need to add them to the parent and do a query nested in that but ye - we shouldn't have testids in the code here as they might cause issues.

2023-05-23 11:50 UTC, LimeWub commented on lib/src/components/pagination/PaginationPopover.tsx
> +        css={{ p: '$4', display: 'flex', flexWrap: 'wrap', gap: '$1' }}
same problem here with usage of gap. I'd try nesting a `<Stack gap={1} />` in this.

2023-05-23 11:50 UTC, LimeWub commented on lib/src/components/pagination/PaginationPopover.tsx
> +}> = ({ onClick }) => {
Why do you need to pass in `onClick`? Can it not just change the page with the same function the regular PaginationItem uses?

2023-05-23 11:50 UTC, LimeWub commented on lib/src/components/pagination/PaginationPreviousButton.tsx
> +      return onClick(goToPreviousPage)
onClick with the function to go to the previous page passed in? What are you trying to do here? Can you explain?

And what's an example usage?

2023-05-23 11:50 UTC, LimeWub commented on lib/src/components/pagination/PaginationPreviousButton.tsx
> +        '&:disabled': {
ActionIcon should be handling its own disabled styles (they might not be the same as we'd like them to but that's an ActionIcon problem) - could we not be passing this opacity here? Or is it really needed? (if it is the actual opacity is 0.3 but again that's an ActionIcon problem)

2023-05-23 11:50 UTC, LimeWub commented on lib/src/components/pagination/pagination-context/PaginationContext.tsx
> +  )
Maybe so that the array keeps having the same js object reference internally and we don't get more re-renders (a new array per render?)

Now if the array itself is actually needed - I don't know/doubt. I think we can probably do everything with simple numbers instead of involving this array ngl.

2023-05-23 11:50 UTC, LimeWub commented on lib/src/components/pagination/types.ts
> +export type Context = {
Why interface and not type, Marty?

2023-05-23 11:50 UTC, LimeWub commented on lib/src/components/pagination/types.ts
> +import { TcolorScheme } from '../../experiments/color-scheme'
I generally don't love having a types file - I usually prefer the types to be next to where they are used as it's simpler to follow/read imo. :/ I have seen it done a few times but I've not been convinced - what benefit do u see to the separate file?

2023-05-23 11:50 UTC, LimeWub commented on lib/src/components/pagination/pagination.constants.ts
> +export const RENDER_SIX_ELEMENTS = 6
I don't think we need these constants or this file.

2023-05-23 11:50 UTC, LimeWub commented on lib/src/components/pagination/PaginationItem.tsx
> +  size: '4px',
is there a variable for that you can use?  `$0`? or `$1`?

2023-05-23 11:53 UTC, LimeWub commented on lib/src/components/pagination/PaginationItem.tsx
> +  size: '4px',
U responded in another comment and am sadge we don't actually have this variable haha. Resolving this one.

2023-05-23 11:57 UTC, mzeenkala23 commented on lib/src/components/pagination/pagination-context/PaginationContext.tsx
> +  )
@LimeWub after a discussion with @Mhoog we will be generating an array of numbers instead an array of objects, and they won't be generated in the provider but the places they are need, so the `popover` component and the `PaginationPages` component

2023-05-23 12:06 UTC, mzeenkala23 commented on documentation/content/components.navigation.pagination.md
> +      The `Pagination` component comes with 3 components that combine to make the `Pagination`. The parent Pagination contains `Pagination.PreviousButton`, `Pagination.Pages`, `Pagination.NextButton`
ohh From out conversation, I thought you said `I think just leave them as they are for now (exposed) and if people keep forgetting them or something we can add a check then` ?

2023-05-23 12:08 UTC, mzeenkala23 commented on documentation/content/components.navigation.pagination.md
> +      `Pagination.NextButton` represents the forwards navigation element. It has a default label of `Next page` but it can also receive a `label` prop to override the default one. This is important f
The popup icon? This comment is under the ``Pagination.NextButton``

2023-05-23 12:10 UTC, mzeenkala23 commented on documentation/content/components.navigation.pagination.md
> +      Above is an example of passing `visibleElementsCount` prop and setting it to 8. The user will see two navigation buttons, an action button to trigger the popover and five page numbers.
@andoulla  correct me if I am wrong, but for this iteration of the `Pagination` Component we wanted to only handle 6 or 8 and anything else was out of scope, right?

2023-05-23 12:13 UTC, mzeenkala23 commented on documentation/content/components.navigation.pagination.md
> +      Above is an example of when we `disabledPages` prop allowing us to render the pagination items for page 1 and 2 as disabled, and using the `indicatedPages` to mark pages 4 and 5 as completed.
ok thanks will rephrase

2023-05-23 12:14 UTC, LimeWub commented on documentation/content/components.navigation.pagination.md
> +        css={{ display: 'flex' }}
yep and I don't expect the user would need to override tbh :o

2023-05-23 12:16 UTC, andoulla commented on lib/src/components/pagination/pagination.constants.ts
> +export const RENDER_SIX_ELEMENTS = 6
I disagree, we have said that we will avoid hardcoded values by creating constants as a general principle. 

Also, this is something we reused in 2 places. hardcoding it, means every time we want to increase the number of elements we would need to find all the places that we have these and change them, where now this is centralised

2023-05-23 12:16 UTC, LimeWub commented on documentation/content/components.navigation.pagination.md
> +      The `Pagination` component comes with 3 components that combine to make the `Pagination`. The parent Pagination contains `Pagination.PreviousButton`, `Pagination.Pages`, `Pagination.NextButton`
Yes but the more I think about it the less I'm convinced it's worth the trouble.
Just for adding the label (which can be addressed/should be addressed the same way as the popover button label)
and the onClick which I'm not really convinced how useful it actually is - and even if it was then it could be done using the same function as the one that's passed into the Pages...

2023-05-23 12:21 UTC, LimeWub commented on lib/src/components/pagination/pagination.constants.ts
> +export const RENDER_SIX_ELEMENTS = 6
because you will change `RENDER_SIX_ELEMENTS` to a value other than `6` in the future?
Imo the only legit place which should be mentioning 6 or 8 would be the Pagination type.

2023-05-23 12:25 UTC, mzeenkala23 commented on lib/src/components/pagination/Pagination.test.tsx
> +  it('renders no popover trigger when we have 4 or less pages', async () => {
sure thing

2023-05-23 13:07 UTC, mzeenkala23 commented on lib/src/components/pagination/Pagination.test.tsx
> +    expect(await screen.findByText(1)).toBeVisible()
This is just to ensure everything is rendered before we continue with the assertions

2023-05-23 13:09 UTC, mzeenkala23 commented on lib/src/components/pagination/Pagination.tsx
> +  css,
sure thing

2023-05-23 13:10 UTC, mzeenkala23 commented on lib/src/components/pagination/Pagination.tsx
> +    visibleElementsCount !== (RENDER_SIX_ELEMENTS || RENDER_EIGHT_ELEMENTS)
Yeah I am going to  remove this conditional check

2023-05-23 13:12 UTC, mzeenkala23 commented on lib/src/components/pagination/Pagination.tsx
> +    <ColorScheme base="grey1" accent="blue1" {...colorScheme}>
sure thing

2023-05-23 13:14 UTC, mzeenkala23 commented on lib/src/components/pagination/Pagination.tsx
> +      <Box css={css}>
yeah good point will change to `Flex` and add the `{...rest}`

2023-05-23 13:21 UTC, mzeenkala23 commented on lib/src/components/pagination/PaginationItem.tsx
> +        bg: '$white !important'
We want the popover variant to have a white bg

2023-05-23 13:21 UTC, mzeenkala23 commented on lib/src/components/pagination/PaginationItem.tsx
> +    isCompleted: {
sure that is a good idea

2023-05-23 13:23 UTC, mzeenkala23 commented on lib/src/components/pagination/PaginationItem.tsx
> +  const isPaginationItemIndicated = Boolean(
good point, making the change

2023-05-23 13:29 UTC, LimeWub commented on lib/src/components/pagination/PaginationItem.tsx
> +  }
I'm not understanding what the desired behaviour is and why `onSelectedPageChange` doesn't cover it. If we could have an example usage for this maybe it'd be easier to understand :)

2023-05-23 13:54 UTC, mzeenkala23 commented on lib/src/components/pagination/PaginationItem.tsx
> +      popover={isPopoverButton}
yeah so when the `PaginationItem` is used in the popover we want the bg colour to be white, so originally I added `css={{bg: '$white !important}}` but got feedback saying it better to make it a variant.

2023-05-23 13:59 UTC, mzeenkala23 commented on lib/src/components/pagination/PaginationItem.tsx
> +      aria-disabled={isPaginationItemDisabled}
when the component is disabled we do get a `disabled` attribute, but on the figma decision documentation it says we should include ` aria-disabled = true` when the component is disabled

2023-05-23 13:59 UTC, mzeenkala23 commented on lib/src/components/pagination/PaginationNextButton.tsx
> +  const isNumber = typeof pages === 'number'
yeah I have made this change

2023-05-23 14:05 UTC, mzeenkala23 commented on lib/src/components/pagination/PaginationPages.tsx
> +    <Flex css={{ gap: '$1' }}>
will do

2023-05-23 14:10 UTC, mzeenkala23 commented on lib/src/components/pagination/PaginationPages.tsx
> +const numOfPaginationItemsToRender = (
Yeah I have just made the update to pass in a number instead of the whole pages list

2023-05-23 14:24 UTC, mzeenkala23 commented on lib/src/components/pagination/PaginationPopover.tsx
> +              isPopoverButton={true}
hmm  tried create `StyledPaginationItemPopover ` but it didn't allow me to change the bg colour. I had to do this in the end if we don't want to make use of variants 

```
<PaginationItem
   key={pageNumber}
   pageNumber={pageNumber}
    css={{bg: '$white !important'}}
    onClick={onClick}
 />
```

2023-05-23 14:25 UTC, MiguelGDLR commented on lib/src/components/pagination/PaginationPreviousButton.tsx
> +        '&:disabled': {
Myrto is right. Sorry for the confusion but in the docs i'm using 30% opacity because we are planning to update ActionIcon to use opacity as a standard for all disabled elements.

2023-05-23 14:29 UTC, mzeenkala23 commented on lib/src/components/pagination/PaginationPopover.tsx
> +          data-testid="popover_trigger"
would it be better if I made the test-id more specific to the pagination component?

2023-05-23 14:41 UTC, mzeenkala23 commented on lib/src/components/pagination/types.ts
> +import { TcolorScheme } from '../../experiments/color-scheme'
This makes it a lot easier to update types when they are in a single file, it more organised especially in my case there are a few duplicate types, so I have created a base type which I don't have to export to multiple different files, thanks to having a type file

2023-05-23 14:43 UTC, mzeenkala23 commented on documentation/content/components.navigation.pagination.md
> +      Above is an example of passing `visibleElementsCount` prop and setting it to 8. The user will see two navigation buttons, an action button to trigger the popover and five page numbers.
yeah this can be always be extended later

2023-05-23 14:48 UTC, mzeenkala23 commented on lib/src/components/pagination/PaginationPreviousButton.tsx
> +        '&:disabled': {
Yes we need the opacity value so that it matches the design

2023-05-23 21:25 UTC, mzeenkala23 commented on lib/src/components/pagination/Pagination.test.tsx
sure thing will add the tests

2023-05-24 07:47 UTC, andoulla commented on lib/src/components/pagination/PaginationItem.tsx
> +    popover: {
We have a common convention set and agreed for a long time now that all boolean values will be prefixed with is/has/should. The convention obviously  has had some exceptions (ie disabled on the button etc as we were getting them closer to the HMTL definition so we can spread the props in)

2023-05-24 07:52 UTC, andoulla commented on lib/src/components/pagination/PaginationPreviousButton.tsx
> +        '&:disabled': {
so the suggestion here is to remove the opacity overwrite and when the actionicon is updated it will just flow through, right?

2023-05-24 07:53 UTC, andoulla approved these changes

2023-05-24 07:53 UTC, andoulla approved these changes

2023-05-24 08:44 UTC, avirati commented on lib/src/components/pagination/PaginationPopover.tsx
> +import { ActionIcon, Icon, Popover } from '..'
```suggestion

import { ActionIcon, Icon, Popover, Stack } from '..'
```

2023-05-24 08:49 UTC, avirati approved these changes

2023-05-24 09:29 UTC, mzeenkala23 commented on lib/src/components/pagination/PaginationItem.tsx
> +    debounce(1000, () => onItemHover?.(pageNumber))
sure thing

2023-05-24 09:29 UTC, mzeenkala23 commented on lib/src/components/pagination/PaginationPopover.tsx
> +import { ActionIcon, Icon, Popover } from '..'
ahh yes good spot

2023-05-24 10:25 UTC, MiguelGDLR reviewed
Really great job Mzi, I left my [UI review here](https://www.figma.com/file/KjgQh7eTwEfJmH6e56k9mX/DS-Documentation?type=design&node-id=11681%3A104899&t=B76ml6HKdxIWVjVj-1)
There's just a couple things and some of them where my mistake sorry.

2023-05-24 14:37 UTC, mzeenkala23 commented on lib/src/components/pagination/pagination-context/PaginationContext.tsx
> +      value={{
no problem I can add this

2023-05-24 14:38 UTC, mzeenkala23 commented on lib/src/components/pagination/pagination.constants.ts
> +export const TRUNCATED_THRESHOLD = 4
its the cut off point for when we should show the ellipsis, so if the pagesCount is larger than the threshold show the elipsis so the user can navigate with the popover

2023-05-24 14:38 UTC, mzeenkala23 commented on lib/src/components/pagination/PaginationPopover.tsx
> +                css={{ bg: '$white !important' }}
so I have created a `styled('button')` so i don't need to use `!importants` and it works well

2023-05-24 14:38 UTC, mzeenkala23 commented on lib/src/components/pagination/pagination-context/PaginationContext.tsx
> +  onItemHover: () => null,
ahaha yeah 🚀

2023-05-24 15:39 UTC, Mhoog commented on lib/src/components/pagination/pagination.helper.ts
> +export const numOfPaginationItemsToRender = (
Based on the name of the function I was expecting a `number` as result instead of a `number[]`.

Might be good to update the name to something like:
```suggestion
export const getPaginationItemsToRender = (
```

2023-05-24 15:56 UTC, Mhoog commented on lib/src/components/pagination/pagination.constants.ts
> +export const RENDER_SIX_ELEMENTS = 6
Agree with @LimeWub, the `TRUNCATED_THRESHOLD`const describes what the value is used for. `RENDER_EIGHT_ELEMENTS` and `RENDER_SIX_ELEMENTS` don't really tell anything.

If we only want to allow two different amounts of elements to be rendered, we should look at a structure where we 'name' these differently imo. Something like:
```ts
enum VisibleElementsAmount {
  LESS = 6,
  MORE = 8
}
```

or
```ts
const VISIBLE_ELEMENTS_AMOUNT_LESS = 6
const VISIBLE_ELEMENTS_AMOUNT_MORE = 8

visibleElementsAmount: 'less' | 'more'

if (visibleElementsAmount === 'less')
  // do something with `VISIBLE_ELEMENTS_AMOUNT_LESS`
```

2023-05-24 16:13 UTC, mzeenkala23 commented on lib/src/components/pagination/Pagination.tsx
> +        >
ahh yes much better. thanks

2023-05-24 16:13 UTC, mzeenkala23 commented on lib/src/components/pagination/pagination.helper.ts
> +export const numOfPaginationItemsToRender = (
yeah good point

2023-05-24 16:13 UTC, mzeenkala23 commented on lib/src/components/pagination/types.ts
> +}
your right we don't anymore, will remove

2023-05-24 16:18 UTC, mzeenkala23 commented on documentation/content/components.navigation.pagination.md
> +      The `Pagination` component comes with 3 components that combine to make the `Pagination`. The parent Pagination contains `Pagination.PreviousButton`, `Pagination.Pages`, `Pagination.NextButton`
Yeah we can remove the onClicks and rely on the onSelectPageChange

2023-05-24 16:20 UTC, mzeenkala23 commented on lib/src/components/pagination/PaginationItem.tsx
> +  '&:focus': {
ahh sure thing will take a look

2023-05-24 16:21 UTC, mzeenkala23 commented on lib/src/components/pagination/PaginationPopover.tsx
> +          label="Open popover pagination"
yeah i have made the update to pass in an object for the labels

2023-05-24 16:21 UTC, mzeenkala23 commented on lib/src/components/pagination/PaginationPopover.tsx
> +}> = ({ onClick }) => {
Have removed the onClick

2023-05-24 16:21 UTC, mzeenkala23 commented on lib/src/components/pagination/PaginationPreviousButton.tsx
> +      return onClick(goToPreviousPage)
The onClick has been removed here also, based of our discussion

2023-05-24 16:27 UTC, mzeenkala23 commented on lib/src/components/pagination/pagination.constants.ts
> +export const RENDER_SIX_ELEMENTS = 6
good point I do like the use of the enum

2023-05-24 16:35 UTC, mzeenkala23 commented on lib/src/components/pagination/Pagination.test.tsx
> +    expect(await screen.findByText(1)).toBeVisible()
yeah tests seem to work without it , will remove

2023-05-24 17:51 UTC, Mhoog commented on lib/src/components/pagination/types.ts
> +  disabledPages?: number[]
Can we remove the `undefined` type here, and default these values to `[]` in the context? That way you don't have to do the `Boolean(..)` checks or optional chaining.

2023-05-24 17:53 UTC, Mhoog commented on lib/src/components/pagination/types.ts
> +  visibleElementsCount?: TVisibleElementsCount
Same with this as the comment below. Could we remove the `undefined` in the context type, and set the default to one of the two values?

It can still be optional in the `Pagination` component props.

2023-05-24 17:59 UTC, Mhoog commented on lib/src/components/pagination/PaginationPreviousButton.tsx
> +> = ({ css }) => {
You could inherit the props from `ActionIcon` instead:

```tsx
const StyledActionIcon = styled(ActionIcon, {
  ...
})

const PaginationPreviousButton = (
  props: React.ComponentProps<typeof StyledActionIcon>
) => {
  ...
  return(
    <StyledActionIcon {...props}>
    ...
  )
}
```

2023-05-24 18:04 UTC, Mhoog commented on lib/src/components/pagination/PaginationPages.tsx
> +  return true
Since you're using `return`, you don't have to use `else if`:

```suggestion
  if (paginationItems?.includes(pagesCount - 1)) return false
  if (pagesCount > truncatedThreshold) return true

  return true
```

2023-05-24 19:57 UTC, mzeenkala23 commented on lib/src/components/pagination/types.ts
> +  disabledPages?: number[]
yeah I can do that

2023-05-24 19:57 UTC, mzeenkala23 commented on lib/src/components/pagination/types.ts
> +  visibleElementsCount?: TVisibleElementsCount
sure thing

2023-05-24 19:58 UTC, mzeenkala23 commented on lib/src/components/pagination/PaginationPreviousButton.tsx
> +> = ({ css }) => {
hmm I believe I have implemented this the way you suggested?

2023-05-24 19:59 UTC, mzeenkala23 commented on lib/src/components/pagination/PaginationPages.tsx
> +  return true
very good point, however I have removed this function as it turns out we didn't need its functionality in the end

2023-05-24 21:17 UTC, Mhoog approved these changes

2023-05-25 07:59 UTC, LimeWub commented on lib/src/components/pagination/PaginationItem.tsx
> +    '&:focus-visible': {
For `focus-visible` You shouldn't need /any/ other styles than the `focusVisibleBlock`.
That includes the BG on this one and the Dot bg. The designs just use the "default"/unhovered etc component state to showcase the outline - but if hovered somehow it keeps the hover styles and so on... :)

2023-05-25 08:00 UTC, LimeWub commented on lib/src/components/pagination/PaginationItem.tsx
> +        '&:focus-visible': {
you also shouldn't need the focus style here - since it'll be the same as above after it's simplified up there.

2023-05-25 10:47 UTC, LimeWub approved these changes
I think you still have some css not needed in the examples in the documentation. But generally - I'm happy with this to get merged :)

2023-05-25 10:50 UTC, MiguelGDLR approved these changes
All good from my side! great job, will create tickets to add other sizes and fix the disabled bug on the future.

2023-05-25 11:19 UTC, merged