Feature: More documentation!
Atom-Learning/components pull request #90
Opened 2021-03-17 15:56 UTC by thomasdigby

2021-03-18 16:02 UTC, andoulla reviewed
I understand why the changelog is excluded, but I wonder if we should have somewhere showing the current version and any migration instructions. It is up for discussion though

2021-03-18 16:02 UTC, andoulla commented on src/documentation/coreconcepts.mdx
> +Each component in the design system is built from a `styled()` function and this gives them access to a series of common props.
Could we link the stitches.mdx here?

2021-03-18 16:38 UTC, thomasdigby commented
> I understand why the changelog is excluded, but I wonder if we should have somewhere showing the current version and any migration instructions. It is up for discussion though

Yep agreed, will add a ticket 👍

2021-03-18 19:43 UTC, thomasdigby commented on src/documentation/coreconcepts.mdx
> +Each component in the design system is built from a `styled()` function and this gives them access to a series of common props.
That sentence is more in relation to the following `as` and `css` props, I can tweak this sentence to make that clear.

2021-03-19 08:39 UTC, andoulla approved these changes

2021-03-19 08:54 UTC, hollg requested changes

2021-03-19 08:54 UTC, hollg commented on src/documentation/coreconcepts.mdx
> +description: There are a few key concepts that underpin our component library, these should help with component composition, encapsulated styling and consistent UI
This isn't quite grammatical. I'm not sure whether we specifically want these descriptions to be one sentence, so I'd suggest either changing to something like this if not:
```
There are a few key concepts that underpin our component library. These should help with component composition, encapsulated styling and consistent UI.
```

Or something like this if we do:

```
Our component library is underpinned by concepts that help with component composition, encapsulated styling and consistent UI
```

2021-03-19 08:54 UTC, hollg commented on src/documentation/coreconcepts.mdx
> +To apply the correct semantic element to one of our components, you can use `as` and pass in a string HTML element. For example, when using the `Heading` component you can pass in `h3` to use that el
This doesn't seem to take into account components like `InputField` where multiple elements are rendered. Is it worth making this more specific?

2021-03-19 08:54 UTC, hollg commented on src/documentation/coreconcepts.mdx
> +The `css` prop is available on all of our components to allow you to style them. You can pass in an object of CSS key value pairs and the component will apply those styles as a class on the rendered
Could we add something about multi-element components and the fact that any styling that affects their internal spacing etc can't be overwritten because they get wrapped in a `Box` / `CSSWrapper` which receives the `css` prop?

2021-03-19 08:54 UTC, hollg commented on src/documentation/stitches.mdx
> +description: Stitches is our styling library of choice, it leans on modern CSS best practices, has near-zero runtime, and provides a great developer experience
```suggestion
description: Stitches is our styling library of choice(. I | because i)t leans on modern CSS best practices, has near-zero runtime, and provides a great developer experience
```

2021-03-19 08:54 UTC, hollg commented on src/documentation/stitches.mdx
> +The full list of utilties below
I feel slightly wary of reproducing the whole list here because it feels like we're setting ourselves up to forget to update it if we update the list in code. Could we give an example and then link to the code for the full list?

2021-03-19 08:54 UTC, hollg commented on src/documentation/versioning.mdx
> +description: The project follows the SemVer standard [Semantic Versioning](https://semver.org/spec/v2.0.0.html) to make using the library easy.
I'm being _super_ picky here but we've got inconsistencies here about where descriptions end with a `.` or not. Can we make them consistent?

2021-03-19 08:58 UTC, andoulla commented on src/documentation/coreconcepts.mdx
> +The `css` prop is available on all of our components to allow you to style them. You can pass in an object of CSS key value pairs and the component will apply those styles as a class on the rendered
I had the same thought yesterday, but I didn't know if it would be duplicating the CSSWrapper doc. It does feel there is a gap here

2021-03-19 09:15 UTC, thomasdigby commented on src/documentation/coreconcepts.mdx
> +To apply the correct semantic element to one of our components, you can use `as` and pass in a string HTML element. For example, when using the `Heading` component you can pass in `h3` to use that el
Added to the second paragraph with `InputField` as an example

2021-03-19 10:09 UTC, thomasdigby commented on src/documentation/stitches.mdx
> +The full list of utilties below
I'm able to embed the _actual_ list of utilities here instead, but it's formatted production code, e.g. `m: () => (e) => ({ margin: e });`.

How do we feel about that compared to linking out to the file?

2021-03-19 10:12 UTC, thomasdigby commented on src/documentation/stitches.mdx
> +The full list of utilties below
It works well with the responsive conditions but less so with the utilities:

![Screenshot 2021-03-19 at 10 12 37](https://user-images.githubusercontent.com/3226804/111764912-a8e7bd00-889b-11eb-962c-11ace6569ff3.png)

2021-03-19 10:19 UTC, andoulla commented on src/documentation/stitches.mdx
> +The full list of utilties below
I don't mind it as our utils are quite simple at the moment. They don't do anything long or complicated for the formating to be a dealbreaker

2021-03-19 10:26 UTC, thomasdigby commented on src/documentation/stitches.mdx
> +The full list of utilties below
Scrapped both, just copying in the conditions for now.

2021-03-19 12:10 UTC, hollg approved these changes

2021-03-19 12:27 UTC, merged